Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2022-08, with the labels that each got.

#137 Task/build error issues
  ActiveForums.csproj
Labels: bug

#124 Change email API usage to use Portal-Specific SMTP configuration
  class/Email.cs
  class/MailQueue.cs
  sql/07.00.00.SqlDataProvider
  sql/FullTextInstallPart2.sql
Labels: enhancement, review in process

#131 Implement ModuleSearchBase for enhanced DNN Platform Search
  Providers/DataProviders/SqlDataProvider/SqlDataProvider.cs
  class/DataProvider.cs
  class/Utilities.cs
  components/Data/Common.cs
  components/Topics/TopicsController.cs
  sql/07.00.00.SqlDataProvider
  sql/Uninstall.SqlDataProvider
Labels: enhancement

#139 Tasks/release prep 6.7.0
  ActiveForums.dnn
  ActiveForums_Symbols.dnn
  Properties/AssemblyInfo.cs
Labels: tasks

#140 Release notes updated for v7.0.
  ReleaseNotes.txt
Labels: tasks

#141 Added missing updates to release notes
  ReleaseNotes.txt
Labels: tasks
