Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2023-06, with the labels that each got.

#192 Some image files in themes are referenced using /images/images/ rather than /images/
  CustomControls/ServerControls/TopicsNavigator.cs
  ReleaseNotes.txt
  config/defaultsetup.config
  config/tokens.config
  controls/af_post.ascx.cs
  controls/af_searchquick.ascx
Labels: bug

#219 Remove redundant indexes on activeforums_ForumTopics
  ActiveForums.csproj
  ActiveForums.dnn
  Properties/AssemblyInfo.cs
  ReleaseNotes.txt
  sql/07.00.08.SqlDataProvider
  sql/Uninstall.SqlDataProvider
Labels: performance

#273 Update namespace references to differentiate between DNN platform and Forums namespaces
  ActiveForumViewerSettings.ascx.cs
  ActiveForums.csproj
  CustomControls/ServerControls/WhatsNewControl.cs
  CustomControls/UserControls/TopicView.cs
  ForumSettings.ascx.cs
  Services/ModerationService.cs
  WhatsNew.ascx.cs
  class/ActiveAdminBase.cs
  class/Email.cs
  class/ForumsConfig.cs
  class/LikesController.cs
  class/SettingsBase.cs
  class/TemplateUtils.cs
  class/UserProfiles.cs
  class/UsersOnline.cs
  class/Utilities.cs
  components/Extensions/ReWriter.cs
  components/Helpers/MoveSettings.cs
  components/Topics/TopicsController.cs
  controls/af_modreport.ascx.cs
  controls/af_quickreply.ascx.cs
Labels: tasks, technical debt

#292 Friendly URL Rewriter updates
  ForumSettings.ascx.cs
  class/ForumsConfig.cs
  components/Extensions/ReWriter.cs
  config/defaultsetup.config
Labels: bug, enhancement

#236 Correct two stored procedures not storing datetime in UTC
  ActiveForums.csproj
  ActiveForums.dnn
  ActiveForums_Symbols.dnn
  Properties/AssemblyInfo.cs
  ReleaseNotes.txt
  sql/07.00.09.SqlDataProvider
Labels: bug

#274 Modernize Likes and move backend to Web API
  ActiveForums.csproj
  Controllers/LikeController.cs
  CustomControls/UserControls/TopicView.cs
  Entities/Like.cs
  ForumSettings.ascx.cs
  Services/Controllers/LikeController.cs
  class/API.cs
  class/ForumsConfig.cs
  class/LikesController.cs
  class/Utilities.cs
  handlers/forumhelper.ashx.cs
  module.css
  scripts/afcommon.js
Labels: enhancement, technical debt, performance

#304 add back missing code lines
  ActiveForums.dnn
  ForumSettings.ascx.cs
  controls/af_post.ascx.cs
Labels: tasks

#307 Tasks/minor build update
  BuildScripts/ModulePackage.targets
  ReleaseNotes.txt
Labels: bug

#308 Merging `dev` into `master` for 07.00.09 Release
  ActiveForumViewerSettings.ascx.cs
  ActiveForums.csproj
  ActiveForums.dnn
  ActiveForums_Symbols.dnn
  BuildScripts/ModulePackage.targets
  Controllers/LikeController.cs
  CustomControls/ServerControls/TopicsNavigator.cs
  CustomControls/ServerControls/WhatsNewControl.cs
  CustomControls/UserControls/TopicView.cs
  Entities/Like.cs
  ForumSettings.ascx
  ForumSettings.ascx.cs
  ForumSettings.ascx.designer.cs
  Properties/AssemblyInfo.cs
  ReleaseNotes.txt
  Services/Controllers/LikeController.cs
  Services/ModerationService.cs
  WhatsNew.ascx.cs
  class/API.cs
  class/ActiveAdminBase.cs
  class/Email.cs
  class/ForumsConfig.cs
  class/LikesController.cs
  class/SettingsBase.cs
  class/TemplateUtils.cs
  class/UserProfiles.cs
  class/UsersOnline.cs
  class/Utilities.cs
  components/Extensions/ReWriter.cs
  components/Helpers/MoveSettings.cs
  components/Topics/TopicsController.cs
  config/defaultsetup.config
  config/tokens.config
  controls/af_modreport.ascx.cs
  controls/af_post.ascx.cs
  controls/af_quickreply.ascx.cs
  controls/af_searchquick.ascx
  handlers/forumhelper.ashx.cs
  module.css
  scripts/afcommon.js
  sql/07.00.07.SqlDataProvider
  sql/07.00.08.SqlDataProvider
  sql/07.00.09.SqlDataProvider
  sql/Uninstall.SqlDataProvider
Labels: tasks

#190 Honor module cache settings when loading templates
  ActiveForums.csproj
  ActiveForums.dnn
  ActiveForums_Symbols.dnn
  App_LocalResources/ControlPanel.ascx.resx
  App_LocalResources/ForumSettings.ascx.resx
  CustomControls/UserControls/ForumView.cs
  CustomControls/UserControls/TopicView.cs
  CustomControls/UserControls/TopicsView.cs
  CustomControls/UserControls/UserProfile.cs
  ForumSettings.ascx
  ForumSettings.ascx.cs
  ForumSettings.ascx.designer.cs
  Properties/AssemblyInfo.cs
  ReleaseNotes.txt
  class/Cache.cs
  class/Globals.cs
  class/Settings.cs
  class/SettingsBase.cs
  class/TemplateCache.cs
  class/TemplateUtils.cs
  components/Common/ForumSettingsBase.cs
  config/defaultsetup.config
Labels: enhancement

#238 Show subscriber counts in Forum, Topics, and Topic views
  ActiveForums.csproj
  App_LocalResources/SharedResources.resx
  CustomControls/UserControls/ForumView.cs
  CustomControls/UserControls/TopicView.cs
  CustomControls/UserControls/TopicsView.cs
  ReleaseNotes.txt
  class/ForumInfo.cs
  config/templates/ForumView.txt
  config/templates/TopicView.txt
  config/templates/TopicsView.txt
  module.css
  sql/07.00.05.SqlDataProvider
  sql/07.00.06.SqlDataProvider
  sql/07.00.07.SqlDataProvider
  sql/07.00.08.SqlDataProvider
  sql/07.00.09.SqlDataProvider
  sql/07.00.10.SqlDataProvider
  themes/_default/module.css
Labels: enhancement

#275 Move Users Online backend to Web API
  ActiveForums.csproj
  Classic.ascx.cs
  Services/Controllers/UserController.cs
  class/UsersOnline.cs
  controls/af_usersonline.ascx.cs
  handlers/forumhelper.ashx.cs
  scripts/afcommon.js
Labels: enhancement, technical debt, performance

#314 Tasks/07.00.10 release prep
  ActiveForums.dnn
  ReleaseNotes.txt
  class/ForumInfo.cs
  class/SettingsBase.cs
  class/TemplateCache.cs
  class/UsersOnline.cs
Labels: tasks

#315 Merging for the 7.0.10 release
  ActiveForums.csproj
  ActiveForums.dnn
  ActiveForums_Symbols.dnn
  App_LocalResources/ControlPanel.ascx.resx
  App_LocalResources/ForumSettings.ascx.resx
  App_LocalResources/SharedResources.resx
  Classic.ascx.cs
  CustomControls/UserControls/ForumView.cs
  CustomControls/UserControls/TopicView.cs
  CustomControls/UserControls/TopicsView.cs
  CustomControls/UserControls/UserProfile.cs
  ForumSettings.ascx
  ForumSettings.ascx.cs
  ForumSettings.ascx.designer.cs
  Properties/AssemblyInfo.cs
  ReleaseNotes.txt
  Services/Controllers/UserController.cs
  class/Cache.cs
  class/ForumInfo.cs
  class/Globals.cs
  class/Settings.cs
  class/SettingsBase.cs
  class/TemplateCache.cs
  class/TemplateUtils.cs
  class/UsersOnline.cs
  components/Common/ForumSettingsBase.cs
  config/defaultsetup.config
  config/templates/ForumView.txt
  config/templates/TopicView.txt
  config/templates/TopicsView.txt
  controls/af_usersonline.ascx.cs
  handlers/forumhelper.ashx.cs
  module.css
  scripts/afcommon.js
  sql/07.00.05.SqlDataProvider
  sql/07.00.06.SqlDataProvider
  sql/07.00.07.SqlDataProvider
  sql/07.00.08.SqlDataProvider
  sql/07.00.09.SqlDataProvider
  sql/07.00.10.SqlDataProvider
  themes/_default/module.css
Labels: tasks

#321 07.00.10 Upgrade fails when executing SQL for 07.00.05
  sql/07.00.05.SqlDataProvider
  sql/07.00.06.SqlDataProvider
  sql/07.00.07.SqlDataProvider
Labels: bug

#249 ENH: Use User's last reply date in flood control
  ActiveForums.csproj
  ActiveForums.dnn
  ActiveForums_Symbols.dnn
  Properties/AssemblyInfo.cs
  ReleaseNotes.txt
  class/UserProfile.cs
  class/Utilities.cs
  components/Users/UserController.cs
  sql/07.00.10.SqlDataProvider
  sql/07.00.11.SqlDataProvider
Labels: enhancement

#297 TASK: Modernize Tokens Entities/Controllers
  ActiveForums.csproj
  Controllers/TokenController.cs
  CustomControls/UserControls/SubmitForm.cs
  CustomControls/UserControls/TopicView.cs
  Entities/Token.cs
  class/Globals.cs
  class/Utilities.cs
Labels: technical debt

#299 ENH: Relocate/remove upgrade code associated with very old versions
  07.00.11.txt
  ActiveForums.csproj
  ActiveForums.dnn
  ControlPanel.ascx.cs
  ReleaseNotes.txt
  class/ForumBase.cs
  class/Settings.cs
  components/Data/Common.cs
  components/Helpers/UpgradeModuleSettings.cs
  components/Topics/TopicsController.cs
  controls/admin_upgrade.ascx
  controls/admin_upgrade.ascx.cs
  controls/admin_upgrade.ascx.designer.cs
Labels: enhancement, technical debt, performance

#312 FIX: Fixes to 'Like' UI
  CustomControls/UserControls/TopicView.cs
  scripts/afcommon.js
Labels: bug

#318 Modulesettings input widths fixes #317
  ForumSettings.ascx
Labels: bug

#323 FIX: Incorrect URL in email notifications
  class/TemplateUtils.cs
Labels: bug

#325 FIX: Bad redirect when replying and using friendly URL rewriter
  components/Replies/Replies.cs
  controls/af_quickreply.ascx.cs
Labels: bug

#327 FIX: Correct behavior when Friendly URLs are disabled but still installed
  CustomControls/HTML/CategoryTreeView.cs
  CustomControls/HTML/ForumContentView.cs
  CustomControls/ServerControls/WhatsNewControl.cs
  CustomControls/UserControls/WhatsNewRSS.cs
  Services/AdminServiceController.cs
  WhatsNew.ascx.cs
  class/TemplateUtils.cs
  class/Utilities.cs
  components/Helpers/URL.cs
  components/Replies/Replies.cs
  components/Topics/TopicsController.cs
  controls/af_quickreply.ascx.cs
Labels: bug

#334 Tasks/release 7.0.11 prep
  ActiveForums.dnn
  ReleaseNotes.txt
Labels: tasks

#337 BUG: Bad redirect when replying and using friendly URL rewriter
  controls/af_post.ascx.cs
Labels: bug

#338 Updated release notes for updates in RC1
  ReleaseNotes.txt
Labels: tasks

#339 Resolved a minor typo
  ReleaseNotes.txt
Labels: tasks

#341 07.00.11 Upgrade fails when executing SQL for 07.00.10
  sql/07.00.10.SqlDataProvider
Labels: bug

#342 Updated release notes
  ReleaseNotes.txt
Labels: tasks

#343 Releasing 07.00.11
  07.00.11.txt
  ActiveForums.csproj
  ActiveForums.dnn
  ActiveForums_Symbols.dnn
  ControlPanel.ascx.cs
  Controllers/TokenController.cs
  CustomControls/HTML/CategoryTreeView.cs
  CustomControls/HTML/ForumContentView.cs
  CustomControls/ServerControls/WhatsNewControl.cs
  CustomControls/UserControls/SubmitForm.cs
  CustomControls/UserControls/TopicView.cs
  CustomControls/UserControls/WhatsNewRSS.cs
  Entities/Token.cs
  ForumSettings.ascx
  ForumSettings.ascx.cs
  Properties/AssemblyInfo.cs
  ReleaseNotes.txt
  Services/AdminServiceController.cs
  WhatsNew.ascx.cs
  class/ForumBase.cs
  class/Globals.cs
  class/Settings.cs
  class/TemplateUtils.cs
  class/UserProfile.cs
  class/Utilities.cs
  components/Data/Common.cs
  components/Helpers/URL.cs
  components/Helpers/UpgradeModuleSettings.cs
  components/Replies/Replies.cs
  components/Topics/TopicsController.cs
  components/Users/UserController.cs
  controls/admin_filters.ascx
  controls/admin_tags.ascx
  controls/admin_templates.ascx
  controls/admin_templates_edit.ascx
  controls/admin_upgrade.ascx
  controls/admin_upgrade.ascx.cs
  controls/admin_upgrade.ascx.designer.cs
  controls/af_post.ascx.cs
  controls/af_quickreply.ascx
  controls/af_quickreply.ascx.cs
  controls/af_usersonline.ascx
  controls/af_usersonline.ascx.designer.cs
  controls/profile_adminsettings.ascx
  scripts/afcommon.js
  sql/07.00.05.SqlDataProvider
  sql/07.00.06.SqlDataProvider
  sql/07.00.07.SqlDataProvider
  sql/07.00.10.SqlDataProvider
  sql/07.00.11.SqlDataProvider
Labels: tasks

#311 ENH: performance improvement in stored procedure activeforums_SaveTopicNextPrev
  ActiveForums.csproj
  sql/07.00.12.SqlDataProvider
Labels: enhancement, performance

#351 TASK: update csproj to remove deprecated items
  ActiveForums.csproj
Labels: tasks

#353 Tasks/7 00 12 rc1 prep
  ActiveForums.csproj
  ActiveForums.dnn
  ActiveForums_Symbols.dnn
  Properties/AssemblyInfo.cs
  ReleaseNotes.txt
Labels: tasks
