Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2023-02, with the labels that each got.

#220 Release 7.0.3
  ActiveForums.dnn
  ActiveForums_Symbols.dnn
  BuildScripts/ModulePackage.targets
  ReleaseNotes.txt
Labels: tasks

#188 Enable IUpgradeable
  ActiveForums.dnn
  components/Topics/TopicsController.cs
Labels: technical debt

#193 Remove (obsolete/legacy) Active Social integration
  ActiveForumViewer.ascx.cs
  ActiveForums.csproj
  ActiveForums.dnn
  ActiveForums_Symbols.dnn
  App_LocalResources/ControlPanel.ascx.resx
  Classic.ascx.cs
  CustomControls/HTML/ControlPanel.cs
  CustomControls/HTML/SecurityGrid.cs
  CustomControls/HTML/TopicViewer.cs
  CustomControls/ServerControls/QuickReply.cs
  CustomControls/UserControls/ForumView.cs
  CustomControls/UserControls/TopicView.cs
  CustomControls/UserControls/TopicsView.cs
  Properties/AssemblyInfo.cs
  ReleaseNotes.txt
  Resources.zip
  WhatsNewResources.zip
  class/ForumGroups.cs
  class/ForumInfo.cs
  class/Globals.cs
  class/Permissions.cs
  class/Settings.cs
  class/Utilities.cs
  components/Extensions/ReWriter.cs
  components/Replies/Replies.cs
  components/Scheduler/DailyDigest.cs
  components/Social/ActiveSocial.cs
  components/Topics/TopicsController.cs
  components/Users/UserController.cs
  controls/admin_home.ascx.cs
  controls/admin_properties.ascx
  controls/admin_properties.ascx.designer.cs
  controls/admin_securitygrid.ascx.cs
  controls/af_members.ascx.cs
  controls/af_modtopics.ascx.cs
  controls/af_post.ascx.cs
  controls/af_quickreply.ascx.cs
  feeds.aspx.cs
  sql/07.00.04.SqlDataProvider
Labels: tasks, technical debt

#210 Fix displayed name for "anonymous" users
  CustomControls/UserControls/TopicsView.cs
Labels: bug

#222 Tasks/release 7.0.4 prep
  ActiveForumViewer.ascx.cs
  ActiveForums.dnn
  ReleaseNotes.txt
  Resources.zip
  WhatsNewResources.zip
Labels: tasks

#240 07.00.04 Release Tasks
  ActiveForumViewer.ascx.cs
  ActiveForums.csproj
  ActiveForums.dnn
  ActiveForums_Symbols.dnn
  App_LocalResources/ControlPanel.ascx.resx
  Classic.ascx.cs
  CustomControls/HTML/ControlPanel.cs
  CustomControls/HTML/SecurityGrid.cs
  CustomControls/HTML/TopicViewer.cs
  CustomControls/ServerControls/QuickReply.cs
  CustomControls/UserControls/ForumView.cs
  CustomControls/UserControls/TopicView.cs
  CustomControls/UserControls/TopicsView.cs
  Properties/AssemblyInfo.cs
  ReleaseNotes.txt
  class/ForumGroups.cs
  class/ForumInfo.cs
  class/Globals.cs
  class/Permissions.cs
  class/Settings.cs
  class/Utilities.cs
  components/Extensions/ReWriter.cs
  components/Replies/Replies.cs
  components/Scheduler/DailyDigest.cs
  components/Social/ActiveSocial.cs
  components/Topics/TopicsController.cs
  components/Users/UserController.cs
  controls/admin_home.ascx.cs
  controls/admin_properties.ascx
  controls/admin_properties.ascx.designer.cs
  controls/admin_securitygrid.ascx.cs
  controls/af_members.ascx.cs
  controls/af_modtopics.ascx.cs
  controls/af_post.ascx.cs
  controls/af_quickreply.ascx.cs
  feeds.aspx.cs
  sql/07.00.04.SqlDataProvider
Labels: tasks

#237 Enhance flood control
  CustomControls/ServerControls/QuickReply.cs
  class/Utilities.cs
  controls/af_post.ascx.cs
  controls/af_quickreply.ascx.cs
Labels: enhancement

#239 Add 'Lock' and 'Pin' actions to TopicView
  CustomControls/UserControls/TopicView.cs
  config/tokens.config
Labels: enhancement

#207 More specific email notification subject lines
  ActiveForums.csproj
  ActiveForums.dnn
  ActiveForums_Symbols.dnn
  App_LocalResources/SharedResources.resx
  Properties/AssemblyInfo.cs
  class/Email.cs
  class/Subscriptions.cs
  class/TemplateUtils.cs
  config/defaultsetup.config
  sql/07.00.05.SqlDataProvider
Labels: enhancement

#244 Version 07.00.05 release prep
  ActiveForums.dnn
  ReleaseNotes.txt
Labels: tasks
