Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2023-11, with the labels that each got.

#573 ENH: Changed Toolbar Icons #550
  Dnn.CommunityForums/class/Utilities.cs
Labels: enhancement

#581 Correction for #501, theme files were missing
  Dnn.CommunityForums/themes/community-default/_less/theme.less
  Dnn.CommunityForums/themes/community-default/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-default/templates/ModAlert.ascx
  Dnn.CommunityForums/themes/community-default/templates/PostApproved.ascx
  Dnn.CommunityForums/themes/community-default/templates/PostDeleted.ascx
  Dnn.CommunityForums/themes/community-default/templates/PostMoved.ascx
  Dnn.CommunityForums/themes/community-default/templates/PostPending.ascx
  Dnn.CommunityForums/themes/community-default/templates/PostRejected.ascx
  Dnn.CommunityForums/themes/community-default/templates/ProfileInfo.ascx
  Dnn.CommunityForums/themes/community-default/templates/QuickReply.ascx
  Dnn.CommunityForums/themes/community-default/templates/ReplyEditor.ascx
  Dnn.CommunityForums/themes/community-default/templates/SubscribedEmail.ascx
  Dnn.CommunityForums/themes/community-default/templates/ToolBar.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicEditor.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
Labels: enhancement

#588 ENH: Add 'most likes' and 'most replies' to toolbar in Community-Default theme
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/themes/community-default/templates/ToolBar.ascx
Labels: enhancement

#596 Moved info to Wiki #595
  Dnn.CommunityForums/themes/README.md
Labels: enhancement, Themes

#592 BUG: 587 collapsed distances
  Dnn.CommunityForums/themes/community-default/_less/parts/_quick-reply.less
  Dnn.CommunityForums/themes/community-default/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-default/templates/QuickReply.ascx
Labels: bug, Themes

#589 Subscribe missing from TopicsView.ascx + add styling fixes #585
  Dnn.CommunityForums/themes/community-default/_less/parts/_topics-view.less
  Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-default/theme.css
Labels: enhancement, Themes

#584 Delivered default theme now "community-default" rather than "community"
  Dnn.CommunityForums/config/defaultsetup.config
Labels: enhancement

#599 Load FontAwesome locally rather than from CDN
  Dnn.CommunityForums/Classic.ascx
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/ControlPanel.ascx.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/HELP-US-OUT.txt
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/css/font-awesome.css
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/css/font-awesome.min.css
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/fonts/FontAwesome.otf
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/fonts/fontawesome-webfont.eot
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/fonts/fontawesome-webfont.svg
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/fonts/fontawesome-webfont.ttf
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/fonts/fontawesome-webfont.woff
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/less/animated.less
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/less/bordered-pulled.less
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/less/core.less
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/less/fixed-width.less
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/less/font-awesome.less
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/less/icons.less
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/less/larger.less
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/less/list.less
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/less/mixins.less
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/less/path.less
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/less/rotated-flipped.less
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/less/screen-reader.less
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/less/stacked.less
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/less/variables.less
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/scss/_animated.scss
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/scss/_bordered-pulled.scss
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/scss/_core.scss
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/scss/_fixed-width.scss
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/scss/_icons.scss
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/scss/_larger.scss
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/scss/_list.scss
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/scss/_mixins.scss
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/scss/_path.scss
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/scss/_rotated-flipped.scss
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/scss/_screen-reader.scss
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/scss/_stacked.scss
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/scss/_variables.scss
  Dnn.CommunityForums/Resources/font-awesome-4.7.0/scss/font-awesome.scss
Labels: enhancement, dependencies

#601 ENH: optionally load {.min}.css variant of theme.css / themes.css
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/ReleaseNotes.txt
  Dnn.CommunityForums/themes/themes.css
Labels: enhancement

#603 ENH: Modernize collapsible sections in topic editor
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/class/Injector.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
  Dnn.CommunityForums/scripts/afutils.js
Labels: enhancement, mobile usability

#604 ENH: Added Custom folder and readme.md fixes #598
  Dnn.CommunityForums/themes/community-default/.gitignore
  Dnn.CommunityForums/themes/community-default/custom/README.md
Labels: enhancement, Themes

#606 generate theme.css and theme.min.css fixes #605
  Dnn.CommunityForums/themes/community-default/gulpfile.js
  Dnn.CommunityForums/themes/community-default/package-lock.json
  Dnn.CommunityForums/themes/community-default/package.json
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
  Dnn.CommunityForums/themes/community-default/theme.min.css.map
Labels: enhancement, Themes
