Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2023-04, with the labels that each got.

#276 Corrections for 07.00.06 RC1
  Classic.ascx.cs
  class/Utilities.cs
  controls/af_attach.ascx.cs
  controls/af_confirmaction.ascx.cs
Labels: bug

#265 Cache retrieval of tokens.config
  components/Tokens/TokensController.cs
Labels: performance

#268 Supporting code for Web API implementation
  ActiveForumViewerSettings.ascx.cs
  ActiveForums.csproj
  ControlPanel.ascx.cs
  CustomControls/ServerControls/UserStats.cs
  CustomControls/UserControls/ForumView.cs
  ForumSettings.ascx.cs
  Services/AdminServiceController.cs
  Services/Controllers/ControllerBase.cs
  Services/ForumAuthorizeAttribute.cs
  Services/RouteMapper.cs
  Services/ServicesHelper.cs
  WhatsNewOptions.ascx.cs
  class/Cache.cs
  class/Email.cs
  class/ForumController.cs
  class/ForumsConfig.cs
  class/Globals.cs
  class/MailQueue.cs
  class/SettingsBase.cs
  class/Subscriptions.cs
  class/TemplateUtils.cs
  controls/af_post.ascx.cs
  controls/af_searchquick.ascx.cs
Labels: enhancement

#272 Remove usage of deprecated DNN platform APIs
  Classic.ascx.cs
  ControlPanel.ascx.cs
  CustomControls/ServerControls/UserStats.cs
  CustomControls/UserControls/TopicView.cs
  CustomControls/UserControls/TopicsView.cs
  CustomControls/UserControls/WhatsNewRSS.cs
  ForumSettings.ascx.cs
  class/SettingsBase.cs
  components/Common/HandlerBase.cs
  components/Users/UserController.cs
  controls/af_attach.ascx.cs
  feeds.aspx.cs
Labels: dependencies, tasks

#217 Add table relationships to use cascading deletes
  ActiveForums.csproj
  ActiveForums.dnn
  ActiveForums_Symbols.dnn
  DAL2/Content/Content.cs
  Properties/AssemblyInfo.cs
  ReleaseNotes.txt
  class/ForumsConfig.cs
  components/Topics/TopicsController.cs
  controls/af_post.ascx
  controls/af_post.ascx.cs
  controls/af_post.ascx.designer.cs
  controls/af_quickreply.ascx
  controls/af_quickreply.ascx.cs
  controls/af_quickreply.ascx.designer.cs
  sql/07.00.07.SqlDataProvider
  sql/Uninstall.SqlDataProvider
Labels: bug

#285 Removed duplicate, added missing var
  class/ForumBase.cs
Labels: bug

#289 Added back commented-out code for a future release
  class/Globals.cs
Labels: tasks

#290 Escaping a single quote
  class/emoticons.cs
Labels: bug
