Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2023-09, with the labels that each got.

#436 ENH: Enable template-based UI for Quick Reply
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/config/defaultsetup.config
  Dnn.CommunityForums/config/templates/QuickReply.txt
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.designer.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.designer.cs
  Dnn.CommunityForums/themes/community/templates/QuickReply.txt
Labels: enhancement, mobile usability

#444 ENH: Remove generic legacy CSS from theme.css
  Dnn.CommunityForums/themes/theme.css
Labels: enhancement, mobile usability

#449 ENH: Add a new Wrapper CSS class
  Dnn.CommunityForums/ActiveForums.ascx
Labels: enhancement

#438 FIX: theme name duplicated in icon URL causing 404 on some pages
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/controls/af_search.ascx.cs
Labels: bug

#256 FIXED: Moving forums or groups up/down in control panel doesn't work in some situations
  Dnn.CommunityForums/sql/08.00.00.SqlDataProvider
Labels: bug

#440 Don't set runAllManagedModulesForAllRequest in web.config
  Dnn.CommunityForums/ReleaseNotes.txt
  Dnn.CommunityForums/components/Extensions/ConfigUtils.cs
Labels: tasks

#452 FIX: Correct issue during 08.00.00 upgrade of templates
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/Templates.cs
Labels: bug, enhancement

#453 FIX: 07.00.12 missing from upgradeVersionsList in manifest
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/components/Topics/TopicsController.cs
Labels: bug

#454 ENH: ~/DesktopModules/ActiveForums/themes/theme.css to themes.css
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/ReleaseNotes.txt
  Dnn.CommunityForums/themes/community/custom/theme.css
  Dnn.CommunityForums/themes/community/theme.css
  Dnn.CommunityForums/themes/themes.css
Labels: enhancement

#331 TASK: Update inconsistently-named variables
  Dnn.CommunityForums/components/Data/ForumsDB.cs
Labels: technical debt

#456 ENH: Remove plaintext email templates
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Providers/DataProviders/SqlDataProvider/SqlDataProvider.cs
  Dnn.CommunityForums/class/DataProvider.cs
  Dnn.CommunityForums/class/Email.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/MailQueue.cs
  Dnn.CommunityForums/class/Subscriptions.cs
  Dnn.CommunityForums/class/TemplateCache.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/class/Templates.cs
  Dnn.CommunityForums/class/UserProfile.cs
  Dnn.CommunityForums/config/defaultsetup.config
  Dnn.CommunityForums/config/templates/AdminWatchEmail_plaintext.txt
  Dnn.CommunityForums/config/templates/ModAlert_plaintext.txt
  Dnn.CommunityForums/config/templates/ModEmail_plaintext.txt
  Dnn.CommunityForums/config/templates/PostApproved_plaintext.txt
  Dnn.CommunityForums/config/templates/PostDeleted_plaintext.txt
  Dnn.CommunityForums/config/templates/PostMoved_plaintext.txt
  Dnn.CommunityForums/config/templates/PostRejected_plaintext.txt
  Dnn.CommunityForums/config/templates/SubscribedEmail_plaintext.txt
  Dnn.CommunityForums/controls/admin_templates_edit.ascx
  Dnn.CommunityForums/controls/admin_templates_edit.ascx.cs
  Dnn.CommunityForums/controls/admin_templates_edit.ascx.designer.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_sendto.ascx.cs
Labels: enhancement, technical debt

#464 ENH: Change elements with CSS class aftitlelg to be H3 tags
  Dnn.CommunityForums/controls/af_members.ascx
  Dnn.CommunityForums/controls/af_members.ascx.designer.cs
  Dnn.CommunityForums/controls/af_modreport.ascx
  Dnn.CommunityForums/controls/af_modreport.ascx.designer.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx
  Dnn.CommunityForums/controls/af_modtopics.ascx.designer.cs
  Dnn.CommunityForums/controls/af_profile.ascx
  Dnn.CommunityForums/controls/af_profile.ascx.designer.cs
Labels: enhancement

#466 ENH: rename an existing "_default" theme to "_legacy"
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/CustomControls/UserControls/UserProfile.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/Settings.cs
  Dnn.CommunityForums/class/TemplateCache.cs
  Dnn.CommunityForums/class/Templates.cs
  Dnn.CommunityForums/components/Common/ForumSettingsBase.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/sql/08.00.00.SqlDataProvider
Labels: enhancement

#487 Add [RESX:Rating] resource string
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
Labels: enhancement

#494 FIX: Clear cached user signature when changed
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/CustomControls/UserControls/Members.cs
  Dnn.CommunityForums/CustomControls/UserControls/UserProfile.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/class/UserProfile.cs
  Dnn.CommunityForums/components/Users/UserController.cs
Labels: bug

#495 ENH: change div to span in search header
  Dnn.CommunityForums/controls/af_searchadvanced.ascx
Labels: bug, enhancement

#498 FIX: "minisearch" needs to know tabid to pass to url generator
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/controls/af_searchquick.ascx.cs
Labels: bug

#499 ENH: module css cleanup
  Dnn.CommunityForums/ControlPanel.css
  Dnn.CommunityForums/module.css
  Dnn.CommunityForums/themes/README.md
  Dnn.CommunityForums/themes/_legacy-module.css
  Dnn.CommunityForums/themes/_legacy/theme.css
  Dnn.CommunityForums/themes/themes.css
Labels: enhancement, technical debt

#257 NEW: Ban User feature for Admins & Moderators
  Dnn.CommunityForums/App_LocalResources/Messages.ascx.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/Controllers/UserController.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Providers/DataProviders/SqlDataProvider/SqlDataProvider.cs
  Dnn.CommunityForums/class/DataProvider.cs
  Dnn.CommunityForums/class/ForumBase.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/config/defaultgroupforums.config
  Dnn.CommunityForums/config/tokens.config
  Dnn.CommunityForums/controls/af_confirmaction.ascx.cs
  Dnn.CommunityForums/controls/af_modban.ascx
  Dnn.CommunityForums/controls/af_modban.ascx.cs
  Dnn.CommunityForums/controls/af_modban.ascx.designer.cs
  Dnn.CommunityForums/sql/08.00.00.SqlDataProvider
  Dnn.CommunityForums/sql/Uninstall.SqlDataProvider
Labels: enhancement

#433 ENH: New UI views for "Most Liked" and "Most Replies"
  ActiveForums.sln
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/CustomControls/ServerControls/Toolbar.cs
  Dnn.CommunityForums/Providers/DataProviders/SqlDataProvider/SqlDataProvider.cs
  Dnn.CommunityForums/class/DataProvider.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/components/Data/Common.cs
  Dnn.CommunityForums/components/Extensions/ReWriter.cs
  Dnn.CommunityForums/config/templates/ToolBar.ascx
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/sql/08.00.00.SqlDataProvider
  Dnn.CommunityForums/sql/Uninstall.SqlDataProvider
Labels: enhancement

#506 FIX: move afSecGrid css back to module.css
  Dnn.CommunityForums/ControlPanel.css
  Dnn.CommunityForums/module.css
Labels: bug

#508 ENH: ctrl+enter to submit on quick reply
  Dnn.CommunityForums/controls/af_quickreply.ascx
Labels: enhancement

#509 ENH: Wrap post editor with banner if moderating another user's post
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/module.css
Labels: enhancement

#511 ENH: Fix legacy theme.css and remove it's module.css fixes #510
  Dnn.CommunityForums/themes/_legacy/module.css
  Dnn.CommunityForums/themes/_legacy/theme.css
Labels: enhancement

#516 FIX: Typo in activeforums_UI_MostReplies stored procedure
  Dnn.CommunityForums/sql/08.00.00.SqlDataProvider
Labels: bug

#517 ENH: Module Branding #490
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/ControlPanel.ascx
  Dnn.CommunityForums/ControlPanel.css
Labels: enhancement

#524 #474 Swap icon texts in span
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/class/Utilities.cs
Labels: enhancement
