Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2023-10, with the labels that each got.

#527 FIX: if no templates loaded, default templates should still work
  Dnn.CommunityForums/class/Email.cs
  Dnn.CommunityForums/class/TemplateCache.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/class/Templates.cs
  Dnn.CommunityForums/controls/admin_templates_edit.ascx.cs
  Dnn.CommunityForums/controls/af_modreport.ascx.cs
Labels: bug

#526 TASK: Remove dead-code & template path variables
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ForumLoader.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/class/ForumBase.cs
Labels: tasks, technical debt

#538 FIX: move subscriptions when moving topic
  Dnn.CommunityForums/sql/08.00.00.SqlDataProvider
Labels: bug

#540 FIX: restore removed code from #527
  Dnn.CommunityForums/class/Templates.cs
Labels: bug

#541 ENH: new collapsible section logic and font awesome icons
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/class/Injector.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
  Dnn.CommunityForums/controls/af_usersonline.ascx
  Dnn.CommunityForums/controls/af_usersonline.ascx.cs
  Dnn.CommunityForums/controls/af_usersonline.ascx.designer.cs
  Dnn.CommunityForums/module.css
  Dnn.CommunityForums/scripts/afcommon.js
  Dnn.CommunityForums/scripts/afutils.js
Labels: enhancement

#548 Corrections for legacy theme after upgrade
  Dnn.CommunityForums/themes/_legacy-module.css
Labels: bug

#555 Update _legacy-module.css
  Dnn.CommunityForums/themes/_legacy-module.css
Labels: bug

#546 FIX: Build issues with unit test project after module was renamed
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForumsTests/DnnCommunityForumsTests.csproj
  Dnn.CommunityForumsTests/Properties/AssemblyInfo.cs
Labels: bug

#558 TASK: Remove not used themes/module.css
  Dnn.CommunityForums/08.00.00.txt
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#561 TASK: Remove ActiveForums.sln.GhostDoc.xml during upgrade
  Dnn.CommunityForums/08.00.00.txt
Labels: tasks

#563 TASK: remove images/ambuttonback.gif
  Dnn.CommunityForums/08.00.00.txt
Labels: tasks

#566 FIX: Can't use wildcards in cleanup file
  Dnn.CommunityForums/08.00.00.txt
Labels: bug, tasks

#567 TASK: remove _master.ascx
  Dnn.CommunityForums/08.00.00.txt
  Dnn.CommunityForums/BuildScripts/ModulePackage.targets
Labels: tasks

#568 FIX: CopyFolder() needs to overwrite existing files
  Dnn.CommunityForums/class/Utilities.cs
Labels: bug

#572 Make the preview window work :-) #557
  Dnn.CommunityForums/controls/af_post.ascx
  Dnn.CommunityForums/module.css
Labels: enhancement

#571 Changed controlpanel.css so links a readabel #570
  Dnn.CommunityForums/ControlPanel.css
Labels: enhancement

#559 TASK: Include readme.md files in installations
  Dnn.CommunityForums/BuildScripts/ModulePackage.targets
  Dnn.CommunityForums/DnnCommunityForums.csproj
Labels: documentation, tasks

#575 ENH: Changed images to FontAwesome icons #522
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
Labels: enhancement

#578 ENH: Improved Quick Search HTML #577
  Dnn.CommunityForums/class/Utilities.cs
Labels: enhancement
