Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2023-08, with the labels that each got.

#403 Exclude illustrator logo/branding source files from build
  Dnn.CommunityForums/BuildScripts/ModulePackage.targets
Labels: tasks

#411 FontAwesome loading part of the solution for #410
  Dnn.CommunityForums/Classic.ascx
Labels: enhancement

#412 Logo documentation fixes #405
  Dnn.CommunityForums/images/Branding/Logo/README.md
Labels: documentation

#394 TASK: Additional 08.00.00 Forums rebranding updates
  .gitignore
  Dnn.CommunityForums/08.00.00.txt
  Dnn.CommunityForums/BuildScripts/ModulePackage.targets
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/ForumsViewerResources.zip
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/sql/08.00.00.SqlDataProvider
Labels: tasks

#418 Feature/410 font awsome loading
  Dnn.CommunityForums/Classic.ascx
Labels: enhancement

#396 FIX: Allow Web APIs to be called from Forums viewer
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ForumLoader.cs
  Dnn.CommunityForums/Services/Controllers/ForumController.cs
  Dnn.CommunityForums/Services/Controllers/TopicController.cs
  Dnn.CommunityForums/scripts/afcommon.js
  Dnn.CommunityForums/scripts/afmod.js
Labels: bug

#424 Add transparent PNG options for Logo
  Dnn.CommunityForums/images/Branding/Logo/DNN-Community-Forums-Logo-Block-BG-White.png
  Dnn.CommunityForums/images/Branding/Logo/DNN-Community-Forums-Logo-Block.png
  Dnn.CommunityForums/images/Branding/Logo/DNN-Community-Forums-Logo-Horizontal-BG-White.png
  Dnn.CommunityForums/images/Branding/Logo/DNN-Community-Forums-Logo-Horizontal.png
  Dnn.CommunityForums/images/Branding/Logo/Illustrator/Logo-Block.ai
  Dnn.CommunityForums/images/Branding/Logo/Illustrator/Logo-Horizontal.ai
Labels: enhancement

#422 Additional 8.0 build updates
  Dnn.CommunityForums/08.00.00.txt
  Dnn.CommunityForums/BuildScripts/ModulePackage.targets
  Dnn.CommunityForums/ForumsViewerResources.zip
Labels: tasks

#426 FIX: Incorrect links in pager when forum does not inherit group settings
  Dnn.CommunityForums/CustomControls/ServerControls/PagerNav.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
Labels: bug

#428 FIX: Web API urls have extra slash
  Dnn.CommunityForums/scripts/afcommon.js
  Dnn.CommunityForums/scripts/afmod.js
Labels: bug

#430 FIX: Forum settings in Control Panel
  Dnn.CommunityForums/CustomControls/ServerControls/ForumLoader.cs
  Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/Services/ForumServiceController.cs
  Dnn.CommunityForums/Services/ModerationService.cs
  Dnn.CommunityForums/class/Email.cs
  Dnn.CommunityForums/class/ForumBase.cs
  Dnn.CommunityForums/class/ForumController.cs
  Dnn.CommunityForums/class/Subscriptions.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/components/Replies/Replies.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
  Dnn.CommunityForums/controls/af_modreport.ascx.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
  Dnn.CommunityForums/handlers/forumhelper.ashx.cs
Labels: bug

#435 FIX: usings missing in forumhelper.ashx.cs
  Dnn.CommunityForums/handlers/forumhelper.ashx.cs
Labels: tasks
