Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2023-03, with the labels that each got.

#259 07.00.05 release merge
  ActiveForums.csproj
  ActiveForums.dnn
  ActiveForums_Symbols.dnn
  App_LocalResources/SharedResources.resx
  CustomControls/ServerControls/QuickReply.cs
  CustomControls/UserControls/TopicView.cs
  Properties/AssemblyInfo.cs
  ReleaseNotes.txt
  class/Email.cs
  class/Subscriptions.cs
  class/TemplateUtils.cs
  class/Utilities.cs
  config/defaultsetup.config
  config/tokens.config
  controls/af_post.ascx.cs
  controls/af_quickreply.ascx.cs
  sql/07.00.05.SqlDataProvider
Labels: tasks

#246 Fix control panel feature popup location
  controls/admin_manageforums_forumeditor.ascx
Labels: bug

#250 Deprecating AMPageBase
  class/AMPageBase.cs
Labels: technical debt

#253 Replace deprecated DNN platform method GetModuleSettings() with .ModuleSettings property references
  ActiveForums.csproj
  Classic.ascx.cs
  ControlPanel.ascx.cs
  CustomControls/UserControls/WhatsNewRSS.cs
  ReleaseNotes.txt
  Services/AdminServiceController.cs
  WhatsNew.ascx.cs
  WhatsNewOptions.ascx.cs
  class/ActiveAdminBase.cs
  class/SettingsBase.cs
  components/Extensions/ReWriter.cs
  components/Topics/TopicsController.cs
Labels: enhancement, performance

#248 fix issue with hidden forum groups not showing if some forums are visible
  CustomControls/UserControls/ForumView.cs
  ReleaseNotes.txt
Labels: bug

#262 v07.00.06 Release Prep
  ActiveForums.dnn
  ReleaseNotes.txt
Labels: tasks
