Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2023-07, with the labels that each got.

#358 FIX: Always create friendly topic URL even if no forum/forum group URL prefix
  ActiveForums.csproj
  ActiveForums.dnn
  Controllers/LikeController.cs
  Controllers/TopicController.cs
  Controllers/UrlController.cs
  CustomControls/ServerControls/QuickReply.cs
  Entities/TopicInfo.cs
  class/ForumsConfig.cs
  components/Data/Topics.cs
  components/Helpers/URL.cs
  components/Replies/Replies.cs
  components/Topics/TopicInfo.cs
  components/Topics/TopicsController.cs
  controls/af_modreport.ascx.cs
  controls/af_modtopics.ascx.cs
  controls/af_post.ascx.cs
  controls/af_quickreply.ascx.cs
  controls/af_sendto.ascx.cs
  handlers/forumhelper.ashx.cs
Labels: bug

#359 FIX: Some features not working correctly from Forums Viewer
  ActiveForumViewer.ascx.cs
  Classic.ascx.cs
  CustomControls/ServerControls/ForumLoader.cs
  CustomControls/UserControls/ForumView.cs
  CustomControls/UserControls/SubmitForm.cs
  CustomControls/UserControls/TopicView.cs
  class/Utilities.cs
  controls/af_usersonline.ascx.cs
Labels: bug

#364 ENH: Use Friendly URLs on my/active/unread topics pages
  controls/af_grid.ascx.cs
Labels: enhancement

#366 Updated release notes
  ReleaseNotes.txt
Labels: tasks

#370 Release 07.00.12
  ActiveForumViewer.ascx.cs
  ActiveForums.csproj
  ActiveForums.dnn
  ActiveForums_Symbols.dnn
  Classic.ascx.cs
  Controllers/LikeController.cs
  Controllers/TopicController.cs
  Controllers/UrlController.cs
  CustomControls/ServerControls/ForumLoader.cs
  CustomControls/ServerControls/QuickReply.cs
  CustomControls/UserControls/ForumView.cs
  CustomControls/UserControls/SubmitForm.cs
  CustomControls/UserControls/TopicView.cs
  CustomControls/UserControls/TopicsView.cs
  Entities/TopicInfo.cs
  Properties/AssemblyInfo.cs
  ReleaseNotes.txt
  class/ForumsConfig.cs
  class/Utilities.cs
  components/Data/Topics.cs
  components/Helpers/URL.cs
  components/Replies/Replies.cs
  components/Topics/TopicInfo.cs
  components/Topics/TopicsController.cs
  controls/af_grid.ascx.cs
  controls/af_modreport.ascx.cs
  controls/af_modtopics.ascx.cs
  controls/af_post.ascx.cs
  controls/af_quickreply.ascx.cs
  controls/af_sendto.ascx.cs
  controls/af_usersonline.ascx.cs
  handlers/forumhelper.ashx.cs
  sql/07.00.12.SqlDataProvider
Labels: tasks

#365 ENH: Improvements to subscriptions UI / move to web API
  Dnn.CommunityForums/ActiveForums.csproj
  Dnn.CommunityForums/Controllers/SubscriptionController.cs
  Dnn.CommunityForums/CustomControls/HTML/ToggleSubscribe.cs
  Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/Entities/SubscriptionInfo.cs
  Dnn.CommunityForums/Services/Controllers/ForumController.cs
  Dnn.CommunityForums/Services/Controllers/TopicController.cs
  Dnn.CommunityForums/class/Subscriptions.cs
  Dnn.CommunityForums/config/templates/TopicView.txt
  Dnn.CommunityForums/config/templates/TopicsView.txt
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.designer.cs
  Dnn.CommunityForums/handlers/forumhelper.ashx.cs
  Dnn.CommunityForums/module.css
  Dnn.CommunityForums/scripts/afcommon.js
  Dnn.CommunityForums/scripts/resx.js
Labels: enhancement, technical debt

#229 ENH: Updated CSS Loading
  Dnn.CommunityForums/ActiveForumViewer.ascx.cs
  Dnn.CommunityForums/ActiveForums.csproj
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ForumLoader.cs
  Dnn.CommunityForums/ReleaseNotes.txt
  Dnn.CommunityForums/class/ForumBase.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/Settings.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/themes/_default/custom/theme.css
  Dnn.CommunityForums/themes/_default/theme.css
  Dnn.CommunityForums/themes/module.css
  Dnn.CommunityForums/themes/theme.css
Labels: enhancement

#227 ENH: Store and retrieve templates to/from file system
  Dnn.CommunityForums/ActiveForums.csproj
  Dnn.CommunityForums/ActiveForums.dnn
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/CustomControls/ServerControls/Toolbar.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/Members.cs
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/CustomControls/UserControls/UserProfile.cs
  Dnn.CommunityForums/class/Cache.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/Settings.cs
  Dnn.CommunityForums/class/SettingsBase.cs
  Dnn.CommunityForums/class/TemplateCache.cs
  Dnn.CommunityForums/class/Templates.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/config/defaultsetup.config
  Dnn.CommunityForums/config/templates/AdminWatchEmail.txt
  Dnn.CommunityForums/config/templates/AdminWatchEmail_plaintext.txt
  Dnn.CommunityForums/config/templates/DailyDigest.txt
  Dnn.CommunityForums/config/templates/ModAlert.txt
  Dnn.CommunityForums/config/templates/ModAlert_plaintext.txt
  Dnn.CommunityForums/config/templates/ModEmail.txt
  Dnn.CommunityForums/config/templates/ModEmail_plaintext.txt
  Dnn.CommunityForums/config/templates/PostApproved.txt
  Dnn.CommunityForums/config/templates/PostApproved_plaintext.txt
  Dnn.CommunityForums/config/templates/PostDeleted.txt
  Dnn.CommunityForums/config/templates/PostDeleted_plaintext.txt
  Dnn.CommunityForums/config/templates/PostMoved.txt
  Dnn.CommunityForums/config/templates/PostMoved_plaintext.txt
  Dnn.CommunityForums/config/templates/PostRejected.txt
  Dnn.CommunityForums/config/templates/PostRejected_plaintext.txt
  Dnn.CommunityForums/config/templates/SubscribedEmail.txt
  Dnn.CommunityForums/config/templates/SubscribedEmail_plaintext.txt
  Dnn.CommunityForums/controls/admin_templates_edit.ascx
  Dnn.CommunityForums/controls/admin_templates_edit.ascx.cs
  Dnn.CommunityForums/controls/admin_templates_edit.ascx.designer.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/sql/08.00.00.SqlDataProvider
Labels: enhancement

#329 TASK: Update for some deprecated DNN methods
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/CustomControls/HTML/ControlPanel.cs
  Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs
  Dnn.CommunityForums/class/Email.cs
  Dnn.CommunityForums/class/ForumController.cs
  Dnn.CommunityForums/class/Permissions.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/components/Replies/Replies.cs
  Dnn.CommunityForums/components/Social/ActiveSocial.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/components/Users/UserController.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
  Dnn.CommunityForums/controls/admin_securitygrid.ascx.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
Labels: dependencies, technical debt

#380 forumsconfig.cs and other compile issues
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/class/ForumBase.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/Settings.cs
  Dnn.CommunityForums/class/SettingsBase.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  website/DesktopModules/ActiveForums/ActiveForums.dnn
Labels: bug

#382 ENH: Improved Caching (PR 270 compile errors)
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/class/Permissions.cs
Labels: tasks

#385 Update WebsitePath in Module.build
  Dnn.CommunityForums/Module.build
Labels: tasks

#386 Remove duplicate templates tag in defaultsetup.config
  Dnn.CommunityForums/config/defaultsetup.config
Labels: bug

#383 Issues/issue 374
  .gitignore
  Dnn.CommunityForums/ActiveForums.csproj
  Dnn.CommunityForums/packages.config
  Dnn.CommunityForumsTests/ActiveForumsTests.csproj
Labels: enhancement

#352 TASK: Modernization to reduce reliance on HttpRequest
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/Controllers/TokenController.cs
  Dnn.CommunityForums/CustomControls/ServerControls/HtmlControlLoader.cs
  Dnn.CommunityForums/CustomControls/ServerControls/TagCloud.cs
  Dnn.CommunityForums/CustomControls/ServerControls/Toolbar.cs
  Dnn.CommunityForums/CustomControls/ServerControls/TopMembers.cs
  Dnn.CommunityForums/CustomControls/ServerControls/UserStats.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/CustomControls/UserControls/WhatsNewRSS.cs
  Dnn.CommunityForums/Services/AdminServiceController.cs
  Dnn.CommunityForums/Services/ForumAuthorizeAttribute.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/class/UserProfiles.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/components/Controls/ControlsConfig.cs
  Dnn.CommunityForums/components/Data/Common.cs
  Dnn.CommunityForums/components/Data/Topics.cs
  Dnn.CommunityForums/components/Helpers/Localization.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/components/Users/UserController.cs
  Dnn.CommunityForums/feeds.aspx.cs
  Dnn.CommunityForums/handlers/adminhelper.ashx.cs
Labels: tasks, technical debt

#388 Issues/issue 280
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.resx
  Dnn.CommunityForums/CustomControls/ServerControls/ActiveGrid.cs
  Dnn.CommunityForums/CustomControls/ServerControls/Callback.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/ForumSettings.ascx
  Dnn.CommunityForums/ForumSettings.ascx.cs
  Dnn.CommunityForums/Module.build
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/config/defaultsetup.config
  Dnn.CommunityForums/controls/_default.ascx
  Dnn.CommunityForums/sql/08.00.00.SqlDataProvider
  Dnn.CommunityForums/themes/community/theme.css
  Dnn.CommunityForumsTests/DnnCommunityForumsTests.csproj
  DnnCommunityForums.sln
  DnnCommunityForums.sln.GhostDoc.xml
  README.md
Labels: enhancement

#393 FIX: Uninstall fails when dropping table activeforums_Tags
  Dnn.CommunityForums/sql/Uninstall.SqlDataProvider
Labels: bug
