Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2023-12, with the labels that each got.

#612 Tasks/8.0 rc1 release notes
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#613 Resolves an HTML display issue in the release notes
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#614 Fixed typos & added a missed feature
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#616 Release notes typos
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#618 ENH: lmprove user experience when upgrading and then setting quick reply template
  Dnn.CommunityForums/config/templates/QuickReply.ascx
  Dnn.CommunityForums/sql/08.00.00.SqlDataProvider
Labels: bug, enhancement

#620 ENH: Made the User column in Post View less wide fixes #619
  Dnn.CommunityForums/themes/community-default/_less/_variables.less
  Dnn.CommunityForums/themes/community-default/_less/parts/_columns.less
  Dnn.CommunityForums/themes/community-default/_less/theme.less
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: enhancement

#624 FIX: Missing delete icon in control panel
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx
Labels: bug

#622 ENH: Use non-circle version of chevron for collapsible icon
  Dnn.CommunityForums/class/Injector.cs
  Dnn.CommunityForums/scripts/afcommon.js
Labels: enhancement

#626 ENH: Added styling for new Chevron Icons #625
  Dnn.CommunityForums/module.css
Labels: enhancement

#628 Fixes #627 Icon text distance
  Dnn.CommunityForums/module.css
Labels: enhancement

#629 fixes #583 Theme nodule_modules exclusing for installer ZIP
  Dnn.CommunityForums/BuildScripts/ModulePackage.targets
Labels: bug
