Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2024-06, with the labels that each got.

#846 ENH: minor CSS tweaks in topic editor
  Dnn.CommunityForums/module.css
Labels: enhancement

#847 ENH: Change DotNetNuke to DNN in resource files
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.de-DE.resx
Labels: documentation, localization

#849 TASK: Remove some obsolete v6 documentation files
  Dnn.CommunityForums/08.01.00.txt
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/Documentation/License.txt
  Dnn.CommunityForums/Documentation/ReleaseNotes.txt
  Dnn.CommunityForums/Documentation/images/af6_icon.jpg
  Dnn.CommunityForums/Documentation/old_ReleaseNotes.txt
Labels: tasks

#843 FIX: Topic with poll creates two topics in database
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/components/Replies/Replies.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
Labels: bug

#848 TASK: remove resource references for removed mail queue option
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.es-ES.resx
  Dnn.CommunityForums/config/defaultsetup.config
Labels: localization, tasks

#851 ENH: Wider subject & summary textboxes
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/config/templates/QuickReply.ascx
  Dnn.CommunityForums/config/templates/TopicEditor.ascx
  Dnn.CommunityForums/module.css
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicEditor.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicEditor.ascx
Labels: enhancement

#852 ENH: Reduce whitespace when not using topic properties or post icons
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/config/templates/TopicEditor.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicEditor.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicEditor.ascx
Labels: enhancement

#853 ENH: Tidy up topic editor
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/config/templates/TopicEditor.ascx
  Dnn.CommunityForums/module.css
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicEditor.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicEditor.ascx
Labels: enhancement

#860 FIX: Subscribe to all forums displaying resource key rather than text when you click on it
  Dnn.CommunityForums/controls/profile_mysubscriptions.ascx
  Dnn.CommunityForums/controls/profile_mysubscriptions.ascx.designer.cs
Labels: bug

#855 FIX: Topic / Forum subscriber counts not incrementing in bootstrap theme
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx
Labels: bug, Themes

#874 Checked and corrected the nl-NL translations
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/Messages.ascx.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
Labels: localization

#875 ENH: Removed the "Enterprise version text" from the language files
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.es-ES.resx
Labels: enhancement, localization, requires more information

#889 ENH: Change default avatar size (250x250 rather than 50x50)
  Dnn.CommunityForums/config/defaultsetup.config
Labels: enhancement

#891 FIX: Show graphic in poll in Community themes
  Dnn.CommunityForums/module.css
Labels: bug

#895 FIX: Evaluate "All Users" and "Unauthenticated Users" in Permissions Controller
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
Labels: bug

#901 FIX: Replace hardcoded "Started by" text with resource string
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/config/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
Labels: bug, localization

#902 Correction for #901 Started By in nl-NL
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
Labels: enhancement, localization

#907 FIX: Allow Friendly URL module setting for multi-language sites
  Dnn.CommunityForums/ForumSettings.ascx.cs
Labels: bug

#905 TASK: Update license and readme
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/README.md
  LICENSE
Labels: documentation, tasks

#912 Fixes Like icon aligning to the left under Bootstrap 5 #911
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_topic-view.scss
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-bootstrap/theme.css
  Dnn.CommunityForums/themes/community-bootstrap/theme.css.map
  Dnn.CommunityForums/themes/community-bootstrap/theme.min.css
Labels: enhancement, themes

#919 Various fixes for regressions found on large / older sites
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/Entities/ForumGroupInfo.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/UserProfiles.cs
  Dnn.CommunityForums/components/Controls/ControlsBase.cs
  Dnn.CommunityForums/components/Users/UserController.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
Labels: bug, enhancement, localization

#920 Tasks/release 8.1
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks
