Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2024-07, with the labels that each got.

#935 fixes #934 alignment of next link
  Dnn.CommunityForums/themes/community-default/_src/less/_utilities.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_group-title.less
  Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: enhancement

#924 FIX: [DISPLAYNAME] not included in email notifications
  Dnn.CommunityForums/CustomControls/HTML/TopicBrowser.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/class/UserProfiles.cs
  Dnn.CommunityForums/class/UsersOnline.cs
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_profile.ascx.cs
  Dnn.CommunityForums/controls/af_search.ascx.cs
  Dnn.CommunityForums/controls/af_sendto.ascx.cs
  Dnn.CommunityForums/feeds.aspx.cs
Labels: bug

#925 TASK: Release notes updates; manifest for 8.1.1
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: documentation, tasks

#940 FIX: moderation notification not sent
  Dnn.CommunityForums/Controllers/ModerationController.cs
Labels: bug

#942 ENH: Add button to top of TopicsView
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_topics-view.less
  Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: enhancement, themes

#944 FIX: Topic/Topics view caching needs to include page size / current page
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/class/Globals.cs
Labels: bug

#951 FIX: Can't mark reply as correct answer
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/Services/Controllers/ReplyController.cs
  Dnn.CommunityForums/Services/Controllers/TopicController.cs
Labels: bug

#954 FIX: Expanded cache key added to handle paging causing exception when saving topic
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
Labels: bug

#955 Preparing for 8.1.1 release
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#956 Sync master and dev
  Dnn.CommunityForums/Controllers/ModerationController.cs
  Dnn.CommunityForums/CustomControls/HTML/TopicBrowser.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
  Dnn.CommunityForums/Services/Controllers/ReplyController.cs
  Dnn.CommunityForums/Services/Controllers/TopicController.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/class/UserProfiles.cs
  Dnn.CommunityForums/class/UsersOnline.cs
  Dnn.CommunityForums/controls/af_grid.ascx
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_profile.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
  Dnn.CommunityForums/controls/af_search.ascx
  Dnn.CommunityForums/controls/af_search.ascx.cs
  Dnn.CommunityForums/controls/af_sendto.ascx.cs
  Dnn.CommunityForums/feeds.aspx.cs
  Dnn.CommunityForums/sql/08.01.01.SqlDataProvider
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/_src/less/_utilities.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_group-title.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_topics-view.less
  Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: tasks

#960 BUG: Make sure Filter dropdown texts are visible on Mobile
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_action-bars.scss
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-bootstrap/theme.css
  Dnn.CommunityForums/themes/community-bootstrap/theme.css.map
  Dnn.CommunityForums/themes/community-bootstrap/theme.min.css
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_action-bars.less
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: enhancement, mobile usability, themes

#963 FIX: Not redirected to new page after submitting edits to an existing reply
  Dnn.CommunityForums/controls/af_post.ascx.cs
Labels: bug

#965 FIX: Clicking 'Save' in control panel on forum that is not inheriting group security restores default security
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: bug

#966 Updates for 08.01.02 GA release
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#967 Sync master and dev
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_action-bars.scss
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-bootstrap/theme.css
  Dnn.CommunityForums/themes/community-bootstrap/theme.css.map
  Dnn.CommunityForums/themes/community-bootstrap/theme.min.css
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_action-bars.less
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: tasks

#974 FIX: Forum icon not changing when new topic
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
Labels: bug, usability

#977 Sync dev and master
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/ReleaseNotes.txt
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
Labels: tasks

#990 TASK: Update csproj for invalid SourceCodeControl attributes
  Dnn.CommunityForums/DnnCommunityForums.csproj
Labels: tasks

#987 TASK: Create 8.2 release
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Labels: tasks

#994 FIX: What's New should only show selected forums
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/WhatsNewOptions.ascx.cs
Labels: bug

#991 TASK: Install and configure StyleCop and Microsoft.CodeAnalysis.NetAnalyzers
  .gitignore
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/StyleCop.json
  Dnn.CommunityForums/app.config
  Dnn.CommunityForums/packages.config
  Dnn.CommunityForumsTests/DnnCommunityForumsTests.csproj
  Dnn.CommunityForumsTests/StyleCop.json
  Dnn.CommunityForumsTests/packages.config
Labels: tasks, technical debt

#996 FIX: Correct update of post count for moderated content
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
Labels: bug

#1003 FIX: Update User Error Message
  Dnn.CommunityForums/scripts/usereditor.js
Labels: bug, moderator tools

#998 FIX: Don't show my settings / my subscriptions after logged out
  Dnn.CommunityForums/Classic.ascx.cs
Labels: enhancement

#1010 FIX: Send topic deleted notification to original poster not to moderators
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
Labels: bug

#1014 TASK: remove duplicated foreign keys; remove embedded "_activeforums_" from FK names
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
  Dnn.CommunityForums/sql/Uninstall.SqlDataProvider
Labels: technical debt, database

#1015 TASK: Remove unneeded indexes
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
  Dnn.CommunityForums/sql/Uninstall.SqlDataProvider
Labels: database

#1016 TASK: Add ModuleId to activeforums_Permissions
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/ForumGroupController.cs
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/Entities/PermissionInfo.cs
  Dnn.CommunityForums/components/Data/Common.cs
  Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Labels: database

#1013 ENH: Some Dutch translation corrections
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.nl-NL.resx
Labels: enhancement, localization

#1017 ENH: Multiple updates for activeforums_UserProfiles
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/CustomControls/HTML/TopicBrowser.cs
  Dnn.CommunityForums/CustomControls/UserControls/Members.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/CustomControls/UserControls/UserProfile.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Providers/DataProviders/SqlDataProvider/SqlDataProvider.cs
  Dnn.CommunityForums/Services/Controllers/UserController.cs
  Dnn.CommunityForums/class/DataProvider.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/SettingsBase.cs
  Dnn.CommunityForums/class/UserProfile.cs
  Dnn.CommunityForums/class/UsersOnline.cs
  Dnn.CommunityForums/components/Data/ProfilesDB.cs
  Dnn.CommunityForums/components/Users/User.cs
  Dnn.CommunityForums/config/templates/_UserProfile.ascx
  Dnn.CommunityForums/controls/af_subscribe.ascx.cs
  Dnn.CommunityForums/controls/af_topicrating.ascx.cs
  Dnn.CommunityForums/controls/af_usersonline.ascx.cs
  Dnn.CommunityForums/controls/profile_mypreferences.ascx.cs
  Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Labels: technical debt, broad scope, database

#1019 TASK: Create 8.2 release (re-do PR #987)
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
Labels: tasks

#1020 FIX: default permissions not set correctly after PR 1016
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/ForumGroupController.cs
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/Entities/ForumGroupInfo.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
Labels: bug
