Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2024-11, with the labels that each got.

#1147 ENH: Minor tweaks to moderation page
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
Labels: enhancement, moderator tools

#1145 TASK: Remove forum configuration XML serialization/deserialization
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ForumGroupRepeater.cs
  Dnn.CommunityForums/CustomControls/Views/ForumDisplay.cs
  Dnn.CommunityForums/class/ForumBase.cs
  Dnn.CommunityForums/components/Controls/ControlsBase.cs
  Dnn.CommunityForums/components/Data/ForumsDB.cs
Labels: technical debt, performance

#1148 FIX: Move old /sql/sql/ files to /sql/
  Dnn.CommunityForums/08.02.00.txt
  Dnn.CommunityForums/BuildScripts/ModulePackage.targets
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
Labels: tasks

#1154 FIX: correct [GROUP] token location in ForumView template
  Dnn.CommunityForums/themes/community-bootstrap/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-default/templates/ForumView.ascx
Labels: bug, usability

#1155 FIX: Filter forum view if group specified on query string
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
Labels: bug

#1157 FIX: Delete forum not working; delete should remove subscriptions
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/ForumGroupController.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
  Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Labels: bug

#1164 TASK: Replace forum list & delete sprocs with DAL2
  Dnn.CommunityForums/ActiveForumViewerSettings.ascx.cs
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/ForumTopicController.cs
  Dnn.CommunityForums/Controllers/ForumUserController.cs
  Dnn.CommunityForums/Controllers/SubscriptionController.cs
  Dnn.CommunityForums/CustomControls/HTML/ControlPanel.cs
  Dnn.CommunityForums/Deprecated/Cache.cs
  Dnn.CommunityForums/ForumSettings.ascx.cs
  Dnn.CommunityForums/Providers/DataProviders/SqlDataProvider/SqlDataProvider.cs
  Dnn.CommunityForums/class/DataProvider.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
  Dnn.CommunityForums/controls/admin_manageforums_home.ascx.cs
Labels: tasks, technical debt

#1165 TASK: replace forum group delete stored procedure with DAL2
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/ForumGroupController.cs
  Dnn.CommunityForums/Providers/DataProviders/SqlDataProvider/SqlDataProvider.cs
  Dnn.CommunityForums/class/DataProvider.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
  Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Labels: tasks, technical debt

#1166 TASK: Move forum / forum group settings to common "FeatureSettings" class
  Dnn.CommunityForums/Controllers/EmailController.cs
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Entities/FeatureSettings.cs
  Dnn.CommunityForums/Entities/ForumGroupInfo.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Services/Controllers/LikeController.cs
  Dnn.CommunityForums/Services/ForumServiceController.cs
  Dnn.CommunityForums/Services/ModerationService.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/class/ForumBase.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
  Dnn.CommunityForums/controls/af_attach.ascx
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
  Dnn.CommunityForums/controls/profile_mysubscriptions.ascx.cs
  Dnn.CommunityForumsTests/class/UtilitiesTests.cs
Labels: tasks, technical debt

#1167 TASK: Update control panel for FeatureSettings class
  Dnn.CommunityForums/Controllers/ForumGroupController.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
Labels: enhancement, tasks

#1169 TASK: Use DotNetNuke.Common.Utilities.RegexUtils.GetCachedRegex
  Dnn.CommunityForums/CustomControls/ServerControls/Callback.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/ForumSettings.ascx.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/feeds.aspx.cs
Labels: tasks, performance

#1173 ENH: update UX for inheritance labels in control panel
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.es-ES.resx
  Dnn.CommunityForums/ControlPanel.css
  Dnn.CommunityForums/controls/admin_manageforums.ascx
  Dnn.CommunityForums/controls/admin_manageforums_home.ascx.cs
Labels: enhancement, administrator

#1178 ENH: token replacement for topic review when replying
  Dnn.CommunityForums/config/templates/ReplyEditor.ascx
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/themes/community-bootstrap/templates/ReplyEditor.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
Labels: bug, usability

#1175 Fix: Moderate button styling #969
  Dnn.CommunityForums/module.css
Labels: moderator tools, usability

#1174 Add StripQuoteTag utility method and use it when posting to journal (…
  Dnn.CommunityForums/ActiveForumViewerSettings.ascx.cs
  Dnn.CommunityForums/Controllers/EmailController.cs
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/ForumGroupController.cs
  Dnn.CommunityForums/Controllers/ForumTrackingController.cs
  Dnn.CommunityForums/Controllers/ForumUserController.cs
  Dnn.CommunityForums/Controllers/PropertyController.cs
  Dnn.CommunityForums/Controllers/TokenController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/Controllers/TopicPropertyController.cs
  Dnn.CommunityForums/Controllers/TopicTrackingController.cs
  Dnn.CommunityForums/CustomControls/HTML/ControlPanel.cs
  Dnn.CommunityForums/CustomControls/ServerControls/Callback.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ForumGroupRepeater.cs
  Dnn.CommunityForums/CustomControls/ServerControls/TagCloud.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/CustomControls/UserControls/UserProfile.cs
  Dnn.CommunityForums/CustomControls/UserControls/WhatsNewRSS.cs
  Dnn.CommunityForums/CustomControls/Views/ForumDisplay.cs
  Dnn.CommunityForums/Deprecated/Utilities.cs
  Dnn.CommunityForums/Entities/AuthorInfo.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Services/AdminServiceController.cs
  Dnn.CommunityForums/Services/Controllers/LikeController.cs
  Dnn.CommunityForums/Services/ProcessQueue.cs
  Dnn.CommunityForums/Services/ServicesHelper.cs
  Dnn.CommunityForums/Services/Tokens/ForumsModuleTokenReplacer.cs
  Dnn.CommunityForums/Services/Tokens/ResourceStringTokenReplacer.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/ViewModels/Topic.cs
  Dnn.CommunityForums/WhatsNew.ascx.cs
  Dnn.CommunityForums/class/Author.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/ParamBuilder.cs
  Dnn.CommunityForums/class/Settings.cs
  Dnn.CommunityForums/class/TemplateCache.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/class/UserProfile.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/components/Common/HandlerBase.cs
  Dnn.CommunityForums/components/Helpers/JSON.cs
  Dnn.CommunityForums/components/Helpers/Localization.cs
  Dnn.CommunityForums/components/Helpers/TextUtils.cs
  Dnn.CommunityForums/components/Helpers/UpgradeModuleSettings.cs
  Dnn.CommunityForums/components/Social/ActiveSocial.cs
  Dnn.CommunityForums/controls/admin_manageforums_home.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_search.ascx.cs
  Dnn.CommunityForums/controls/af_searchadvanced.ascx.cs
  Dnn.CommunityForums/controls/af_searchquick.ascx.cs
  Dnn.CommunityForums/controls/profile_mypreferences.ascx.cs
  Dnn.CommunityForums/feeds.aspx.cs
  Dnn.CommunityForums/handlers/adminhelper.ashx.cs
  Dnn.CommunityForumsTests/class/UtilitiesTests.cs
Labels: enhancement, technical debt, performance, usability

#1176 ENH: Move email notification subject template to forum settings
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.es-ES.resx
  Dnn.CommunityForums/ControlPanel.css
  Dnn.CommunityForums/Controllers/EmailController.cs
  Dnn.CommunityForums/Entities/FeatureSettings.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.designer.cs
Labels: enhancement, technical debt, administrator
