Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2024-04, with the labels that each got.

#722 FIX: modal UI issues
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/active/amlib.js
  Dnn.CommunityForums/controls/htmlcontrols/quickedit.ascx
Labels: bug

#723 ENH: Show toolbar in My Settings
  Dnn.CommunityForums/ActiveForums.ascx.cs
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/Controllers/LikeController.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ForumLoader.cs
  Dnn.CommunityForums/CustomControls/UserControls/UserProfile.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Entities/Like.cs
  Dnn.CommunityForums/class/ForumController.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/ProfileBase.cs
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/controls/af_profile.ascx.cs
  Dnn.CommunityForums/controls/profile_mypreferences.ascx
  Dnn.CommunityForums/controls/profile_mypreferences.ascx.cs
  Dnn.CommunityForums/controls/profile_mypreferences.ascx.designer.cs
Labels: enhancement

#719 TASK: Modernizes Permissions-related code to use DAL2
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/Controllers/FilterController.cs
  Dnn.CommunityForums/Controllers/LikeController.cs
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/Controllers/RepositoryControllerBase.cs
  Dnn.CommunityForums/CustomControls/HTML/ForumContentView.cs
  Dnn.CommunityForums/CustomControls/HTML/ForumDirectory.cs
  Dnn.CommunityForums/CustomControls/HTML/SecurityGrid.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ForumRow.cs
  Dnn.CommunityForums/CustomControls/ServerControls/Link.cs
  Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs
  Dnn.CommunityForums/CustomControls/ServerControls/TopicsNavigator.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/Deprecated/Utilities.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Entities/PermissionInfo.cs
  Dnn.CommunityForums/Services/AdminServiceController.cs
  Dnn.CommunityForums/Services/ForumServiceController.cs
  Dnn.CommunityForums/Services/ServicesHelper.cs
  Dnn.CommunityForums/class/ForumBase.cs
  Dnn.CommunityForums/class/ForumController.cs
  Dnn.CommunityForums/class/ForumGroups.cs
  Dnn.CommunityForums/class/ForumInfo.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/Permissions.cs
  Dnn.CommunityForums/class/SettingsBase.cs
  Dnn.CommunityForums/class/Subscriptions.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/components/Common/HandlerBase.cs
  Dnn.CommunityForums/components/Data/Common.cs
  Dnn.CommunityForums/components/Filters/FilterController.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/controls/admin_securitygrid.ascx.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_quickjump.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
  Dnn.CommunityForums/controls/af_searchadvanced.ascx.cs
  Dnn.CommunityForums/controls/af_sendto.ascx.cs
  Dnn.CommunityForums/feeds.aspx.cs
  Dnn.CommunityForums/handlers/adminhelper.ashx.cs
  Dnn.CommunityForums/handlers/forumhelper.ashx.cs
  Dnn.CommunityForums/viewer.aspx.cs
  Dnn.CommunityForumsTests/Controllers/PermissionControllerTests.cs
  Dnn.CommunityForumsTests/DnnCommunityForumsTests.csproj
Labels: tasks, technical debt, performance

#728 ENH: Moderator notifications when banning user
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/controls/af_modban.ascx.cs
  Dnn.CommunityForums/sql/08.01.00.SqlDataProvider
Labels: enhancement

#737 TASK: Modernize Topics to use DAL2
  Dnn.CommunityForums/Controllers/ForumGroupController.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Providers/DataProviders/SqlDataProvider/SqlDataProvider.cs
  Dnn.CommunityForums/Services/Controllers/TopicController.cs
  Dnn.CommunityForums/Services/ForumServiceController.cs
  Dnn.CommunityForums/Services/ModerationService.cs
  Dnn.CommunityForums/class/Content.cs
  Dnn.CommunityForums/class/DataProvider.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/components/Replies/Replies.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/controls/admin_securitygrid.ascx.cs
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/controls/af_modreport.ascx.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
  Dnn.CommunityForums/controls/af_search.ascx.cs
  Dnn.CommunityForums/controls/af_sendto.ascx.cs
  Dnn.CommunityForums/handlers/forumhelper.ashx.cs
Labels: enhancement, tasks, technical debt

#738 TASK: Modernize Replies to use DAL2
  Dnn.CommunityForums/Controllers/ForumGroupController.cs
  Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs
  Dnn.CommunityForums/DAL2/Reply/Reply.cs
  Dnn.CommunityForums/DAL2/Reply/ReplyController.cs
  Dnn.CommunityForums/Deprecated/API.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Services/ForumServiceController.cs
  Dnn.CommunityForums/Services/ModerationService.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/components/Data/Topics.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/controls/af_modreport.ascx.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
  Dnn.CommunityForums/handlers/forumhelper.ashx.cs
  components/Replies/ReplyInfo.cs
Labels: enhancement, tasks, technical debt

#739 TASK: Modernize Tags/Categories to use DAL2
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/TagController.cs
  Dnn.CommunityForums/Controllers/TopicCategoryController.cs
  Dnn.CommunityForums/Controllers/TopicTagController.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Entities/CategoryInfo.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TagInfo.cs
  Dnn.CommunityForums/Entities/TopicCategoryInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Entities/TopicTagInfo.cs
  Dnn.CommunityForums/class/Subscriptions.cs
Labels: enhancement, tasks, technical debt

#730 BUG: Exclude Themes\**\custom\*.css from install package
  Dnn.CommunityForums/BuildScripts/ModulePackage.targets
Labels: bug

#745 TASK: Minor tweaks to Topic and Reply Web APIs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Services/Controllers/ReplyController.cs
  Dnn.CommunityForums/Services/Controllers/TopicController.cs
  Dnn.CommunityForums/scripts/afcommon.js
  Dnn.CommunityForums/scripts/afmod.js
Labels: tasks, technical debt

#746 Modernize topic properties to use DAL2
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/PropertyController.cs
  Dnn.CommunityForums/Controllers/TopicPropertyController.cs
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Entities/PropertyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Entities/TopicPropertyInfo.cs
  Dnn.CommunityForums/components/Data/PropertiesDB.cs
  Dnn.CommunityForums/components/Properties/PropertiesController.cs
  Dnn.CommunityForums/components/Properties/PropertiesInfo.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/handlers/adminhelper.ashx.cs
  Dnn.CommunityForums/handlers/forumhelper.ashx.cs
  Dnn.CommunityForums/scripts/afmod.js
  Dnn.CommunityForumsTests/Controllers/TopicPropertyControllerTests.cs
  Dnn.CommunityForumsTests/DnnCommunityForumsTests.csproj
  Dnn.CommunityForumsTests/class/UtilitiesTests.cs
Labels: tasks, technical debt

#747 ENH: User Subscription Manager
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/SubscriptionController.cs
  Dnn.CommunityForums/CustomControls/ServerControls/Toolbar.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Entities/SubscriptionInfo.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/components/Extensions/ReWriter.cs
  Dnn.CommunityForums/config/templates/ToolBar.ascx
  Dnn.CommunityForums/controls/profile_mysubscriptions.ascx
  Dnn.CommunityForums/controls/profile_mysubscriptions.ascx.cs
  Dnn.CommunityForums/controls/profile_mysubscriptions.ascx.designer.cs
  Dnn.CommunityForums/module.css
  Dnn.CommunityForums/sql/08.01.00.SqlDataProvider
  Dnn.CommunityForums/themes/community-bootstrap/templates/ToolBar.ascx
  Dnn.CommunityForums/themes/community-default/templates/ToolBar.ascx
Labels: enhancement

#751 Modernize topic tags to use DAL2
  Dnn.CommunityForums/Controllers/TagController.cs
  Dnn.CommunityForums/Controllers/TopicTagController.cs
  Dnn.CommunityForums/CustomControls/HTML/TopicBrowser.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Entities/TopicTagInfo.cs
  Dnn.CommunityForums/Providers/DataProviders/SqlDataProvider/SqlDataProvider.cs
  Dnn.CommunityForums/Services/Controllers/TagController.cs
  Dnn.CommunityForums/Services/Controllers/TopicController.cs
  Dnn.CommunityForums/class/DataProvider.cs
  Dnn.CommunityForums/controls/admin_categories.ascx.cs
  Dnn.CommunityForums/controls/admin_tags.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/handlers/forumhelper.ashx.cs
  Dnn.CommunityForumsTests/class/UtilitiesTests.cs
Labels: tasks, technical debt

#752 TASK: Modernize email notification queue
  Dnn.CommunityForums/Controllers/EmailController.cs
  Dnn.CommunityForums/Controllers/EmailNotificationQueueController.cs
  Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Entities/EmailInfo.cs
  Dnn.CommunityForums/Entities/EmailNotificationQueueInfo.cs
  Dnn.CommunityForums/Providers/DataProviders/SqlDataProvider/SqlDataProvider.cs
  Dnn.CommunityForums/Services/EmailNotificationQueue.cs
  Dnn.CommunityForums/Services/ModerationService.cs
  Dnn.CommunityForums/class/DataProvider.cs
  Dnn.CommunityForums/class/Email.cs
  Dnn.CommunityForums/class/MailQueue.cs
  Dnn.CommunityForums/class/Subscriptions.cs
  Dnn.CommunityForums/controls/af_modreport.ascx.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/controls/af_sendto.ascx.cs
  Dnn.CommunityForums/sql/08.01.00.SqlDataProvider
  Dnn.CommunityForums/sql/Uninstall.SqlDataProvider
Labels: tasks, technical debt

#755 FIX: null value for portalSettings from search crawler
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/components/Controls/ControlUtils.cs
Labels: bug

#756 ENH: changes to subscription options
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
  Dnn.CommunityForums/controls/af_subscribe.ascx.cs
  Dnn.CommunityForums/scripts/afcommon.js
  Dnn.CommunityForums/scripts/resx.js
Labels: enhancement

#758 Change activeforums_EmailNotificationQueue Id column from int to bigint/long
  Dnn.CommunityForums/Entities/EmailNotificationQueueInfo.cs
  Dnn.CommunityForums/sql/08.01.00.SqlDataProvider
Labels: tasks

#757 ENH: Remove journal items when banning user
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/Controllers/UserController.cs
  Dnn.CommunityForums/components/Social/ActiveSocial.cs
  Dnn.CommunityForums/controls/af_modban.ascx.cs
  Dnn.CommunityForums/sql/08.01.00.SqlDataProvider
  Dnn.CommunityForums/sql/Uninstall.SqlDataProvider
Labels: enhancement

#763 ENH: Bootstrap Theme Fixes #762
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_bootstrap.scss
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_icons.scss
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/theme.scss
  Dnn.CommunityForums/themes/community-bootstrap/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-bootstrap/theme.css
  Dnn.CommunityForums/themes/community-bootstrap/theme.css.map
  Dnn.CommunityForums/themes/community-bootstrap/theme.min.css
Labels: enhancement

#766 ENH: fixes #742 prev next class
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_topic-view.less
  Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: enhancement, Themes

#767 Default theme: subscribe alignment right #765
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_subscribe.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_topic-view.less
  Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: enhancement

#768 Fixes for #764
  Dnn.CommunityForums/themes/community-bootstrap/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_forum-view.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_table.less
  Dnn.CommunityForums/themes/community-default/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: enhancement, Themes

#771 ENH: CSS class changes #769
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_topic-controls.scss
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/theme.scss
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-bootstrap/theme.css
  Dnn.CommunityForums/themes/community-bootstrap/theme.css.map
  Dnn.CommunityForums/themes/community-bootstrap/theme.min.css
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_quick-reply.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_subscribe.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_topic-view.less
  Dnn.CommunityForums/themes/community-default/_src/less/theme.less
  Dnn.CommunityForums/themes/community-default/templates/QuickReply.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: enhancement, Themes

#773 ENH: Feature/772 extra space
  Dnn.CommunityForums/themes/community-bootstrap/templates/QuickReply.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_group-title.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_topics-view.less
  Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: enhancement, Themes
