Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2024-10, with the labels that each got.

#1095 ENH: Use template caching module setting for Forums toolbar
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/class/Utilities.cs
Labels: enhancement

#1099 ENH: add wrapper DIVs
  Dnn.CommunityForums/controls/af_grid.ascx
  Dnn.CommunityForums/controls/af_search.ascx
Labels: enhancement, themes

#1104 TASK: Add indexes to retrieve Topics and Replies by ContentId
  Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
  Dnn.CommunityForums/sql/Uninstall.SqlDataProvider
Labels: performance, database

#1108 ENH: More organized security in control panel
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.es-ES.resx
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/Entities/PermissionInfo.cs
  Dnn.CommunityForums/controls/admin_securitygrid.ascx.cs
Labels: enhancement, moderator tools, usability

#1114 FIX: Images inside a post should have a max with of 100%
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/_mixins.scss
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/_src/less/_mixins.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_topic-view.less
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: enhancement

#1110 ENH: New Template for Search Results
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/config/templates/SearchResults.ascx
  Dnn.CommunityForums/controls/af_search.ascx
  Dnn.CommunityForums/controls/af_search.ascx.cs
  Dnn.CommunityForums/controls/af_search.ascx.designer.cs
Labels: enhancement, technical debt

#1109 TASK: Add exception handling to Web API methods
  Dnn.CommunityForums/Services/Controllers/ControllerBase.cs
  Dnn.CommunityForums/Services/Controllers/ForumController.cs
  Dnn.CommunityForums/Services/Controllers/LikeController.cs
  Dnn.CommunityForums/Services/Controllers/ReplyController.cs
  Dnn.CommunityForums/Services/Controllers/TagController.cs
  Dnn.CommunityForums/Services/Controllers/TopicController.cs
  Dnn.CommunityForums/Services/Controllers/UserController.cs
  Dnn.CommunityForums/Services/ForumAuthorizeAttribute.cs
  Dnn.CommunityForums/Services/ServicesHelper.cs
Labels: tasks, technical debt

#1111 ENH: New Template for Filtered Topic Results
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/config/templates/TopicResults.ascx
  Dnn.CommunityForums/controls/af_grid.ascx
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/controls/af_grid.ascx.designer.cs
  Dnn.CommunityForums/controls/af_search.ascx
  Dnn.CommunityForums/controls/af_search.ascx.cs
Labels: enhancement

#1120 ENH: Token updates for ProfileInfo templates
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/themes/community-bootstrap/templates/ProfileInfo.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-default/templates/ProfileInfo.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
Labels: enhancement, themes

#1121 FIX: Correction for #982
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/_mixins.scss
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/theme.scss
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-bootstrap/theme.css
  Dnn.CommunityForums/themes/community-bootstrap/theme.css.map
  Dnn.CommunityForums/themes/community-bootstrap/theme.min.css
Labels: enhancement

#1123 ENH: Toolbar: Move HTML markup to code template and use token replacements
  Dnn.CommunityForums/App_LocalResources/LegacyTokenResources.resx
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Services/Tokens/ForumsModuleTokenReplacer.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/config/templates/ToolBar.ascx
  Dnn.CommunityForums/controls/af_search.ascx.cs
  Dnn.CommunityForums/themes/community-bootstrap/templates/ToolBar.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-default/templates/ToolBar.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
Labels: enhancement, themes

#1125 ENH: Load nested templates using [DCF:TEMPLATE-xxxx] token
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/class/ForumBase.cs
  Dnn.CommunityForums/class/TemplateCache.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/class/Utilities.cs
Labels: enhancement

#1132 TASK: Refactoring CurrentUserType
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/Members.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/CustomControls/UserControls/UserProfile.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/class/SettingsBase.cs
  Dnn.CommunityForums/class/TemplateCache.cs
  Dnn.CommunityForums/controls/af_members.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/profile_adminsettings.ascx.cs
  Dnn.CommunityForums/controls/profile_mypreferences.ascx.cs
  Dnn.CommunityForums/controls/profile_mysubscriptions.ascx.cs
Labels: tasks, technical debt

#1130 ENH: Use token replacement for moderation notifications
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/Controllers/ModerationController.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/class/TemplateCache.cs
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/controls/af_search.ascx.cs
  Dnn.CommunityForumsTests/Services/Tokens/TokenReplacerTests.cs
Labels: enhancement, moderator tools

#1133 ENH: Remove duplicated templates
  Dnn.CommunityForums/08.02.00.txt
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/ReleaseNotes.txt
  Dnn.CommunityForums/config/templates/PostPending.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/AdminWatchEmail.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/ModAlert.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/PostApproved.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/PostDeleted.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/PostMoved.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/PostPending.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/PostRejected.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/SubscribedEmail.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/ToolBar.ascx
  Dnn.CommunityForums/themes/community-default/templates/AdminWatchEmail.ascx
  Dnn.CommunityForums/themes/community-default/templates/ModAlert.ascx
  Dnn.CommunityForums/themes/community-default/templates/PostApproved.ascx
  Dnn.CommunityForums/themes/community-default/templates/PostDeleted.ascx
  Dnn.CommunityForums/themes/community-default/templates/PostMoved.ascx
  Dnn.CommunityForums/themes/community-default/templates/PostPending.ascx
  Dnn.CommunityForums/themes/community-default/templates/PostRejected.ascx
  Dnn.CommunityForums/themes/community-default/templates/ReplyEditor.ascx
  Dnn.CommunityForums/themes/community-default/templates/SubscribedEmail.ascx
  Dnn.CommunityForums/themes/community-default/templates/ToolBar.ascx
Labels: tasks, themes

#1134 TASK: Remove obsolete "hiddenstats"
  Dnn.CommunityForums/config/templates/ForumView.ascx
  Dnn.CommunityForums/config/templates/TopicsView.ascx
  Dnn.CommunityForums/module.css
  Dnn.CommunityForums/themes/_legacy-module.css
Labels: tasks, technical debt

#1135 ENH: Token replacement for email template
  Dnn.CommunityForums/App_LocalResources/LegacyTokenResources.resx
  Dnn.CommunityForums/Controllers/EmailController.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/Entities/ForumGroupInfo.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Services/ModerationService.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/class/Subscriptions.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/config/templates/SubscribedEmail.ascx
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/themes/community-bootstrap/templates/ProfileInfo.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-default/templates/ProfileInfo.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
Labels: enhancement, technical debt, themes

#1136 ENH: new tokens for login links
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/Controllers/EmailController.cs
  Dnn.CommunityForums/Controllers/ModerationController.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/Entities/ForumGroupInfo.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/Entities/IPostInfo.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Services/Tokens/ForumsModuleTokenReplacer.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/class/Subscriptions.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/controls/af_search.ascx.cs
  Dnn.CommunityForums/module.css
  Dnn.CommunityForumsTests/Services/Tokens/TokenReplacerTests.cs
Labels: enhancement

#1138 ENH: add upgrade logic for email subject tokens for existing installations
  Dnn.CommunityForums/Services/Tokens/ForumsModuleTokenReplacer.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/config/defaultsetup.config
Labels: enhancement

#1141 FIX: Topic View issues found during pre-release testing
  Dnn.CommunityForums/Controllers/TokenController.cs
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
Labels: bug, usability

#1143 ENH: Use token replacement for like buttons
  Dnn.CommunityForums/App_LocalResources/LegacyTokenResources.resx
  Dnn.CommunityForums/Controllers/LikeController.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/Entities/IPostInfo.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/scripts/afcommon.js
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
Labels: enhancement, themes

#1144 ENH: Font awesome icon for "correct answer"
  Dnn.CommunityForums/App_LocalResources/LegacyTokenResources.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/config/templates/PostActions.ascx
  Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Labels: themes, usability
