Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2024-09, with the labels that each got.

#1060 TASK: Add GetLastPostSubjectLinkTag method to ForumController
  Dnn.CommunityForums/Controllers/ForumController.cs
Labels: tasks, technical debt

#1062 ENH: New message resources for token replacement
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/class/ForumBase.cs
  Dnn.CommunityForums/class/Settings.cs
Labels: enhancement, tasks, moderator tools

#1066 TASK: various updates
  Dnn.CommunityForums/Controllers/EmailController.cs
  Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs
  Dnn.CommunityForums/class/Email.cs
  Dnn.CommunityForums/class/ParamBuilder.cs
  Dnn.CommunityForums/class/UserProfiles.cs
  Dnn.CommunityForums/class/Utilities.cs
Labels: tasks, technical debt

#1068 TASK: Additional method signature for GetDisplayName ForumUserController
  Dnn.CommunityForums/Controllers/ForumUserController.cs
  Dnn.CommunityForums/Services/Controllers/ForumController.cs
  Dnn.CommunityForums/Services/Controllers/UserController.cs
  Dnn.CommunityForums/class/UserProfiles.cs
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_profile.ascx.cs
  Dnn.CommunityForums/controls/af_search.ascx.cs
  Dnn.CommunityForums/controls/af_usersonline.ascx.cs
Labels: tasks, technical debt

#1070 ENH: Implements TokenReplace & IPropertyAccess for primary Forums entites
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/ForumUserController.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/CustomControls/HTML/TopicBrowser.cs
  Dnn.CommunityForums/CustomControls/Views/ForumDisplay.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Entities/AuthorInfo.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Entities/ForumTrackingInfo.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/Entities/IPostInfo.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Entities/TopicTrackingInfo.cs
  Dnn.CommunityForums/Services/Tokens/ResourceStringTokenReplacer.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
Labels: enhancement, tasks, technical debt

#1071 FIX: Build issue due to missing method
  Dnn.CommunityForums/Entities/TopicInfo.cs
Labels: bug

#1072 TASK: duplicated SQL for one procedure
  Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Labels: tasks, database

#1074 FIX: Corrected typo in 08.02.00.SqlDataProvider
  Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Labels: bug

#1080 FIX: Exception loading module settings
  Dnn.CommunityForums/ForumSettings.ascx.cs
  Dnn.CommunityForums/components/Helpers/UpgradeModuleSettings.cs
Labels: bug

#1082 Issues/forum viewer 1081
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs
  Dnn.CommunityForums/CustomControls/ServerControls/Toolbar.cs
  Dnn.CommunityForums/CustomControls/Views/ForumDisplay.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/class/ForumBase.cs
  Dnn.CommunityForums/components/Controls/ControlUtils.cs
  Dnn.CommunityForums/components/Controls/ControlsConfig.cs
Labels: bug

#1083 FIX: User Online status not set correctly
  Dnn.CommunityForums/Controllers/ForumUserController.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
Labels: enhancement

#1085 TASK: Add NewtonSoft JSON package via NuGet
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/app.config
  Dnn.CommunityForums/packages.config
  Dnn.CommunityForumsTests/app.config
Labels: dependencies, tasks

#1087 TASK: Update NUnit & Moq
  Dnn.CommunityForumsTests/DnnCommunityForumsTests.csproj
  Dnn.CommunityForumsTests/packages.config
Labels: dependencies

#1090 FIX: Process Queue issues
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/CustomControls/HTML/CategoriesList.cs
  Dnn.CommunityForums/CustomControls/HTML/ForumContentView.cs
  Dnn.CommunityForums/CustomControls/HTML/TopicBrowser.cs
  Dnn.CommunityForums/CustomControls/ServerControls/TagCloud.cs
  Dnn.CommunityForums/CustomControls/ServerControls/WhatsNewControl.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/CustomControls/UserControls/WhatsNewRSS.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Services/ProcessQueue.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/WhatsNew.ascx.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/components/Controls/ControlUtils.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/controls/af_modreport.ascx.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
Labels: bug

#1091 ENH: Enable move topic to hidden forum
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Services/Controllers/ForumController.cs
  Dnn.CommunityForums/class/ForumController.cs
  Dnn.CommunityForums/controls/af_quickjump.ascx.cs
  Dnn.CommunityForums/controls/af_searchadvanced.ascx.cs
  Dnn.CommunityForums/controls/htmlcontrols/movetopic.ascx
Labels: enhancement, usability

#1093 Correct database integrity issues found during 8.2 testing against DN…
  Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Labels: database
