Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2024-12, with the labels that each got.

#1180 FIX: Improve the "Forum is moderated" message #999
  Dnn.CommunityForums/controls/af_confirmaction.ascx
  Dnn.CommunityForums/controls/af_confirmaction.ascx.designer.cs
  Dnn.CommunityForums/module.css
Labels: enhancement

#1186 FIX: incorrect array size for social group security in module settings
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.resx
  Dnn.CommunityForums/ForumSettings.ascx.cs
Labels: bug, administrator

#1187 FIX: security option labels missing in module settings for social group security
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.resx
  Dnn.CommunityForums/ForumSettings.ascx.cs
Labels: bug, administrator

#1193 FIX: What's new not loading forums
  Dnn.CommunityForums/Controllers/ForumController.cs
Labels: bug

#1197 FIX: Wrong signature displayed in forum posts
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
Labels: bug

#1196 FIX: Feature/1117 styling review
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_topic-view.scss
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_topics-view.scss
  Dnn.CommunityForums/themes/community-bootstrap/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-bootstrap/theme.css
  Dnn.CommunityForums/themes/community-bootstrap/theme.css.map
  Dnn.CommunityForums/themes/community-bootstrap/theme.min.css
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_forum-view.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_topic-view.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_topics-view.less
  Dnn.CommunityForums/themes/community-default/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: enhancement

#1200 Fix: 982 Responsive images in Bootstrap Theme
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_topic-view.scss
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_topics-view.scss
  Dnn.CommunityForums/themes/community-bootstrap/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/ProfileInfo.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-bootstrap/theme.css
  Dnn.CommunityForums/themes/community-bootstrap/theme.css.map
  Dnn.CommunityForums/themes/community-bootstrap/theme.min.css
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_forum-view.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_topic-view.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_topics-view.less
  Dnn.CommunityForums/themes/community-default/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-default/templates/ProfileInfo.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: bug

#1202 FIX: missing topic icons
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/class/Utilities.cs
Labels: bug, usability

#1201 Revert "Fix: 982 Responsive images in Bootstrap Theme"
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_topic-view.scss
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_topics-view.scss
  Dnn.CommunityForums/themes/community-bootstrap/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/ProfileInfo.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-bootstrap/theme.css
  Dnn.CommunityForums/themes/community-bootstrap/theme.css.map
  Dnn.CommunityForums/themes/community-bootstrap/theme.min.css
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_forum-view.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_topic-view.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_topics-view.less
  Dnn.CommunityForums/themes/community-default/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-default/templates/ProfileInfo.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: invalid

#1203 FIX: Post Images Responsive 982
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_topic-view.scss
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-bootstrap/theme.css
  Dnn.CommunityForums/themes/community-bootstrap/theme.css.map
  Dnn.CommunityForums/themes/community-bootstrap/theme.min.css
Labels: enhancement

#1205 FIX: likes views not working with old/non-friendly URLs
  Dnn.CommunityForums/components/Controls/ControlUtils.cs
Labels: bug

#1204 ENH: Basic cleanup for Search results and Filtered Topics
  Dnn.CommunityForums/config/templates/SearchResults.ascx
  Dnn.CommunityForums/config/templates/TopicResults.ascx
  Dnn.CommunityForums/module.css
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_search-results.less
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: enhancement

#1208 ENH: Like notifications
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/Controllers/ForumUserController.cs
  Dnn.CommunityForums/Controllers/LikeController.cs
  Dnn.CommunityForums/Controllers/ModerationController.cs
  Dnn.CommunityForums/Controllers/ProcessQueueController.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/Entities/ProcessQueueInfo.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Services/Controllers/LikeController.cs
  Dnn.CommunityForums/Services/Controllers/TopicController.cs
  Dnn.CommunityForums/Services/ModerationService.cs
  Dnn.CommunityForums/Services/ProcessQueue.cs
  Dnn.CommunityForums/Services/ProcessType.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/components/Replies/Replies.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
  Dnn.CommunityForums/controls/profile_mypreferences.ascx
  Dnn.CommunityForums/controls/profile_mypreferences.ascx.cs
  Dnn.CommunityForums/controls/profile_mypreferences.ascx.designer.cs
  Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Labels: enhancement, usability

#1207 FIX: 1192 Boostrap Theme Table padding
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_all.scss
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_topics-view.scss
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-bootstrap/theme.css
  Dnn.CommunityForums/themes/community-bootstrap/theme.css.map
  Dnn.CommunityForums/themes/community-bootstrap/theme.min.css
Labels: enhancement

#1211 FIX: issues with pin/lock UI
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/config/templates/PostActions.ascx
  Dnn.CommunityForums/config/templates/TopicActions.ascx
  Dnn.CommunityForums/scripts/afcommon.js
Labels: bug, usability

#1213 FIX: correct caching issue when loading topics/replies
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/ForumGroupController.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/RepositoryControllerBase.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
Labels: bug

#1217 FIX: issues found during upgrade testing
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
Labels: bug

#1219 FIX: Multiple records created in activeforums_UserProfiles for same user
  Dnn.CommunityForums/Controllers/ForumUserController.cs
  Dnn.CommunityForums/CustomControls/UserControls/UserProfile.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/controls/profile_mypreferences.ascx.cs
  Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Labels: bug, database

#1220 ENH: User preference to enable email notifications to poster
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Entities/ContentInfo.cs
  Dnn.CommunityForums/Entities/ForumGroupInfo.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/Entities/LikeInfo.cs
  Dnn.CommunityForums/Entities/PermissionInfo.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/Subscriptions.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
  Dnn.CommunityForums/controls/profile_mypreferences.ascx
  Dnn.CommunityForums/controls/profile_mypreferences.ascx.cs
  Dnn.CommunityForums/controls/profile_mypreferences.ascx.designer.cs
  Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Labels: enhancement, database

#1221 FIX: few minor issues encountered in pre-release testing
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/ControlPanel.css
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/Entities/FeatureSettings.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/Entities/PermissionInfo.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/controls/admin_manageforums_home.ascx.cs
  Dnn.CommunityForumsTests/Controllers/PermissionControllerTests.cs
Labels: enhancement, administrator

#1222 Sorting permission set members causing issues
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
Labels: tasks
