Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2024-03, with the labels that each got.

#694 EHN: Moved less files to _src folder fixes #693
  Dnn.CommunityForums/themes/community-default/_src/less/_mixins.less
  Dnn.CommunityForums/themes/community-default/_src/less/_utilities.less
  Dnn.CommunityForums/themes/community-default/_src/less/_variables.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_action-bars.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_breadcrumbs.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_collapse.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_columns.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_edit.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_forum-view.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_group-title.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_old/_control-panel.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_old/_controlpanel.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_pager.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_quick-reply.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_search-advanced.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_search-results.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_subscribe.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_table-responsive.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_table.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_toolbar.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_topic-view.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_topics-view.less
  Dnn.CommunityForums/themes/community-default/_src/less/theme.less
  Dnn.CommunityForums/themes/community-default/gulpfile.js
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
Labels: enhancement

#706 ENH: Added subscriber counts to topics / topic view in community-default theme
  Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
Labels: enhancement

#674 Refactoring: Centralize use of MapPath()
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/Deprecated/Utilities.cs
  Dnn.CommunityForums/ForumSettings.ascx.cs
  Dnn.CommunityForums/class/ForumBase.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/Logger.cs
  Dnn.CommunityForums/class/TemplateCache.cs
  Dnn.CommunityForums/class/Templates.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/controls/admin_ranks.ascx.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/viewer.aspx.cs
Labels: technical debt

#677 ENH: Split Forum Group inheritance for security vs features/settings
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx
  Dnn.CommunityForums/Deprecated/API.cs
  Dnn.CommunityForums/Providers/DataProviders/SqlDataProvider/SqlDataProvider.cs
  Dnn.CommunityForums/class/DataProvider.cs
  Dnn.CommunityForums/class/ForumController.cs
  Dnn.CommunityForums/class/ForumGroups.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.designer.cs
  Dnn.CommunityForums/controls/admin_securitygrid.ascx.cs
  Dnn.CommunityForums/handlers/adminhelper.ashx.cs
Labels: enhancement

#696 FIX: missing spaces in 08.01.00.SqlDataProvider causing installer error
  Dnn.CommunityForums/sql/08.01.00.SqlDataProvider
Labels: bug

#683 Refactoring: ControllerBase and RepositoryControllerBase for DAL2
  Dnn.CommunityForums/Controllers/ControllerBase.cs
  Dnn.CommunityForums/Controllers/RepositoryControllerBase.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/class/Data/AttachmentsDB.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/components/Social/ActiveSocial.cs
  Dnn.CommunityForums/controls/admin_securitygrid.ascx.cs
Labels: technical debt

#698 FIX: Can't subscribe when adding new topic
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/scripts/afcommon.js
Labels: bug

#691 TASK: Centralize string constants and use interpolation
  Dnn.CommunityForums/ActiveForums.ascx.cs
  Dnn.CommunityForums/CustomControls/HTML/CategoryTreeView.cs
  Dnn.CommunityForums/CustomControls/HTML/ForumContentView.cs
  Dnn.CommunityForums/CustomControls/ServerControls/CategoryNavigator.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ForumLoader.cs
  Dnn.CommunityForums/CustomControls/ServerControls/PagerNav.cs
  Dnn.CommunityForums/CustomControls/ServerControls/Toolbar.cs
  Dnn.CommunityForums/CustomControls/ServerControls/TopicsNavigator.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/ForumSettings.ascx.cs
  Dnn.CommunityForums/Services/ForumAuthorizeAttribute.cs
  Dnn.CommunityForums/class/ForumBase.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/Permissions.cs
  Dnn.CommunityForums/class/SettingsBase.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/components/Controls/ControlUtils.cs
  Dnn.CommunityForums/components/Extensions/ReWriter.cs
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/controls/af_modban.ascx.cs
  Dnn.CommunityForums/controls/af_modreport.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_search.ascx.cs
  Dnn.CommunityForums/controls/af_searchadvanced.ascx.cs
  Dnn.CommunityForums/controls/af_searchquick.ascx.cs
  Dnn.CommunityForums/controls/profile_mypreferences.ascx.cs
  Dnn.CommunityForums/handlers/forumhelper.ashx.cs
Labels: tasks, technical debt

#695 FIX: CSS and URL issues with Forum Viewer module
  Dnn.CommunityForums/ActiveForumViewer.ascx
  Dnn.CommunityForums/ActiveForumViewer.ascx.cs
  Dnn.CommunityForums/class/Utilities.cs
Labels: bug

#700 FIX: Prevent JavaScript error using moderator tools in topics view
  Dnn.CommunityForums/ActiveForumViewer.ascx
  Dnn.CommunityForums/ActiveForums.ascx
  Dnn.CommunityForums/scripts/afutils.js
Labels: bug

#709 Unanswered Topics view should exclude locked topics
  Dnn.CommunityForums/sql/08.01.00.SqlDataProvider
Labels: enhancement

#712 Duplicated module when placing on page
  Dnn.CommunityForums/sql/08.01.00.SqlDataProvider
Labels: bug

#716 FIX: URL prefix (vanity name) not saved for Forum Group in Control Panel
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
Labels: bug

#687 TASK: Update NUnit & Moq for Unit Test Project
  Dnn.CommunityForumsTests/DnnCommunityForumsTests.csproj
  Dnn.CommunityForumsTests/app.config
  Dnn.CommunityForumsTests/class/UtilitiesTests.cs
  Dnn.CommunityForumsTests/packages.config
Labels: dependencies, tasks

#704 TASK: Remove obsolete timezone offset settings and code
  Dnn.CommunityForums/Deprecated/Utilities.cs
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/Settings.cs
  Dnn.CommunityForums/class/SettingsBase.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/components/Helpers/UpgradeModuleSettings.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/config/defaultsetup.config
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/controls/af_search.ascx.cs
Labels: tasks, technical debt

#708 ENH: Use PortalSettings to retrieve role IDs for "Registered Users" and "Administrators"
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/class/ForumController.cs
  Dnn.CommunityForums/class/ForumGroups.cs
  Dnn.CommunityForums/class/Permissions.cs
  Dnn.CommunityForums/class/Utilities.cs
Labels: technical debt

#718 ENH: Updates to topic/reply editor UI
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/config/templates/ReplyEditor.ascx
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/themes/community-default/templates/ReplyEditor.ascx
Labels: enhancement
