Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2024-05, with the labels that each got.

#770 FIX: Fix some search-related issues
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/controls/af_search.ascx.cs
Labels: bug

#776 FIX: Insert missing security option for social group in module settings
  Dnn.CommunityForums/ForumSettings.ascx.cs
  Dnn.CommunityForums/components/Common/ForumSettingsBase.cs
  Dnn.CommunityForums/components/Helpers/UpgradeModuleSettings.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
Labels: bug

#777 TASK: Final tweaks before 8.1
  Dnn.CommunityForums/ActiveForumViewerSettings.ascx.cs
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.resx
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/CustomControls/HTML/SecurityGrid.cs
  Dnn.CommunityForums/CustomControls/HTML/TopicViewer.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ActiveTabs.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/CustomControls/UserControls/WhatsNewRSS.cs
  Dnn.CommunityForums/Deprecated/Cache.cs
  Dnn.CommunityForums/Deprecated/Utilities.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/ForumSettings.ascx.cs
  Dnn.CommunityForums/Providers/DataProviders/SqlDataProvider/SqlDataProvider.cs
  Dnn.CommunityForums/Services/AdminServiceController.cs
  Dnn.CommunityForums/Services/Controllers/ForumController.cs
  Dnn.CommunityForums/Services/Controllers/ReplyController.cs
  Dnn.CommunityForums/Services/Controllers/TagController.cs
  Dnn.CommunityForums/Services/Controllers/TopicController.cs
  Dnn.CommunityForums/Services/ModerationService.cs
  Dnn.CommunityForums/class/Cache.cs
  Dnn.CommunityForums/class/DataProvider.cs
  Dnn.CommunityForums/class/ForumController.cs
  Dnn.CommunityForums/class/Subscriptions.cs
  Dnn.CommunityForums/class/UserProfiles.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/controls/admin_home.ascx.cs
  Dnn.CommunityForums/controls/admin_securitygrid.ascx.cs
  Dnn.CommunityForums/controls/af_members.ascx.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_posticonlist.ascx.cs
  Dnn.CommunityForumsTests/Controllers/TopicPropertyControllerTests.cs
Labels: tasks, performance

#782 FIX: Reply not posting (correct) ReplyId to Process Queue :(
  Dnn.CommunityForums/controls/af_post.ascx.cs
Labels: bug

#787 Right align [next] fixes #786
  Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
Labels: bug, Themes

#793 FIX: LastPostId needs to be a calculated property in the ForumInfo entity
  Dnn.CommunityForums/Entities/ForumInfo.cs
Labels: bug

#785 ENH: Show login link on TopicView page if unauthenticated rather than "you are not authorized"
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
Labels: enhancement

#794 FIX: Fix friendly url for latest post on Forums View
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/components/Controls/ControlUtils.cs
Labels: bug

#795 ENH: support [GROUPNAME] [FORUMGROUPID] tokens in [GROUP] section in ForumView
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/themes/community-bootstrap/templates/ForumView.ascx
Labels: enhancement

#796 ENH: New UI 'Filters' toolbar and views for 'Announcements and 'Unresolved'
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/CustomControls/ServerControls/Toolbar.cs
  Dnn.CommunityForums/Providers/DataProviders/SqlDataProvider/SqlDataProvider.cs
  Dnn.CommunityForums/class/DataProvider.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/components/Data/Common.cs
  Dnn.CommunityForums/components/Extensions/ReWriter.cs
  Dnn.CommunityForums/config/templates/ToolBar.ascx
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/module.css
  Dnn.CommunityForums/sql/08.01.00.SqlDataProvider
  Dnn.CommunityForums/sql/Uninstall.SqlDataProvider
  Dnn.CommunityForums/themes/community-bootstrap/templates/ToolBar.ascx
  Dnn.CommunityForums/themes/community-default/templates/ToolBar.ascx
Labels: enhancement

#797 FIX: Moderator action buttons not styled
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/module.css
Labels: bug

#799 FIX: Issues with executing moderation actions from Activity Feed Notifications
  Dnn.CommunityForums/Services/ModerationService.cs
Labels: bug

#804 ENH: Fix for Bootstrap Forum view borders
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_bootstrap.scss
  Dnn.CommunityForums/themes/community-bootstrap/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-bootstrap/theme.css
  Dnn.CommunityForums/themes/community-bootstrap/theme.css.map
  Dnn.CommunityForums/themes/community-bootstrap/theme.min.css
Labels: enhancement, Themes

#806 Fixes #805 Bootstrap Theme Sub Forums Align
  Dnn.CommunityForums/themes/community-bootstrap/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
Labels: bug, Themes

#810 ENH: Change 'Filters' in toolbar to 'Filtered Topics'
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/config/templates/ToolBar.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/ToolBar.ascx
  Dnn.CommunityForums/themes/community-default/templates/ToolBar.ascx
Labels: enhancement

#800 ENH: Add 'ban user' options to forum moderation
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/Controllers/EmailController.cs
  Dnn.CommunityForums/Controllers/ModerationController.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/Controllers/UserController.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/Deprecated/Utilities.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/Services/ModerationService.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/components/Extensions/ReWriter.cs
  Dnn.CommunityForums/controls/af_modreport.ascx.cs
  Dnn.CommunityForums/controls/af_modtopics.ascx
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/sql/08.01.00.SqlDataProvider
Labels: enhancement

#809 FIX: Search results should be visible to unauthenticated users
  Dnn.CommunityForums/components/Topics/TopicsController.cs
Labels: bug

#812 ENH: Add French translations
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/Messages.ascx.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/WhatsNew.ascx.fr-FR.resx
  Dnn.CommunityForums/DnnCommunityForums.csproj
Labels: localization

#811 ENH: Add German Translations
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/Messages.ascx.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/WhatsNew.ascx.de-DE.resx
  Dnn.CommunityForums/DnnCommunityForums.csproj
Labels: localization

#813 ENH: Add Spanish translations
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/Messages.ascx.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/WhatsNew.ascx.es-ES.resx
  Dnn.CommunityForums/DnnCommunityForums.csproj
Labels: localization

#814 ENH: Add Italian translations
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/Messages.ascx.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/WhatsNew.ascx.it-IT.resx
  Dnn.CommunityForums/DnnCommunityForums.csproj
Labels: localization

#815 ENH: Update Dutch translations
  Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/Messages.ascx.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/WhatsNew.ascx.nl-NL.resx
  Dnn.CommunityForums/DnnCommunityForums.csproj
Labels: localization

#817 Tasks/build fixes
  Dnn.CommunityForums/Controllers/ModerationController.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/controls/af_modtopics.ascx.cs
Labels: bug

#818 Updated release notes
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#819 Updated release notes
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#827 Reviewed spanish translation
  Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/Messages.ascx.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/WhatsNew.ascx.es-ES.resx
Labels: localization

#840 Fixed a minor release note typo
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#833 FIX: Missing translations
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/controls/af_usersonline.ascx
  Dnn.CommunityForums/controls/profile_mypreferences.ascx
  Dnn.CommunityForums/controls/profile_mysubscriptions.ascx
Labels: localization

#834 FIX: Add missing French translations
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
Labels: localization

#837 FIX: HTML decoding needed for subject & summary in topics view
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
Labels: bug

#838 FIX: Search Popup needs z-index
  Dnn.CommunityForums/controls/profile_mypreferences.ascx
  Dnn.CommunityForums/module.css
Labels: bug

#839 ENH: Locale-specific caching
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/CustomControls/ServerControls/Toolbar.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
Labels: bug, enhancement

#841 ENH: Use template for search popup
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/config/templates/ToolbarSearchPopup.ascx
Labels: enhancement, localization

#844 ENH: Tweaks to streamline topic editor
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/scripts/afcommon.js
Labels: enhancement
