Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2025-03, with the labels that each got.

#1337 FIX: Issues with "ban user" feature
  Dnn.CommunityForums/Controllers/ForumUserController.cs
Labels: bug, administrator

#1342 TASK: Remove embedded resources for scripts and custom controls images
  Dnn.CommunityForums/CustomControls/ServerControls/ActiveGrid.cs
  Dnn.CommunityForums/CustomControls/ServerControls/Callback.cs
  Dnn.CommunityForums/CustomControls/ServerControls/DatePicker.cs
  Dnn.CommunityForums/CustomControls/ServerControls/MenuButton.cs
  Dnn.CommunityForums/CustomControls/ServerControls/RequiredFieldValidator.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ScriptLoader.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/WhatsNewOptions.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_topicscripts.ascx.cs
Labels: tasks, technical debt

#1345 TASK: Remove 3rd-party SimulateDateDiff
  Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/SimulateDateDiff.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
  Dnn.CommunityForumsTests/Services/Tokens/TokenReplacerTests.cs
  Dnn.CommunityForumsTests/class/UtilitiesTests.cs
Labels: technical debt

#1339 FIX: tweaks to filtered topic results template
  Dnn.CommunityForums/config/templates/TopicResults.ascx
Labels: bug, usability

#1344 TASK: Refactor TabId access when constructing URLs
  Dnn.CommunityForums/Entities/ForumGroupInfo.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Entities/LikeInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
Labels: tasks, technical debt

#1349 ENH: Updates advanced search page to use localization
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/controls/af_searchadvanced.ascx
  Dnn.CommunityForums/controls/af_searchadvanced.ascx.cs
  Dnn.CommunityForums/controls/af_searchadvanced.ascx.designer.cs
Labels: enhancement, localization, usability

#1355 FIX: Advanced Search screen styling
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_search.scss
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/theme.scss
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-bootstrap/theme.css
  Dnn.CommunityForums/themes/community-bootstrap/theme.css.map
  Dnn.CommunityForums/themes/community-bootstrap/theme.min.css
Labels: enhancement

#1356 ENHANCEMENT: Needed a different variation of the Logo
  Dnn.CommunityForums/images/Branding/Logo/Illustrator/Logo-Horizontal.ai
Labels: enhancement

#1358 FIX: Bootstrap Theme Pager spacing #1331
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_pager.scss
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/theme.scss
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-bootstrap/theme.css
  Dnn.CommunityForums/themes/community-bootstrap/theme.css.map
  Dnn.CommunityForums/themes/community-bootstrap/theme.min.css
Labels: enhancement

#1361 FIX: Token replacement should not remove <br /> tags from content
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
Labels: bug, usability

#1362 FIX: Allow Enter key in search box without interfering with other controls on page
  Dnn.CommunityForums/config/templates/ToolbarSearchPopup.ascx
Labels: bug, usability

#1363 FIX: TabId property stackoverflow in ForumInfo/ForumGroupInfo
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/Controllers/UrlController.cs
  Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
  Dnn.CommunityForums/Entities/ForumGroupInfo.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Services/Controllers/TopicController.cs
  Dnn.CommunityForums/Services/ModerationService.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
Labels: bug

#1364 FIX: Refactor to avoid intermittant exceptions when replying
  Dnn.CommunityForums/controls/af_post.ascx.cs
Labels: bug

#1366 Issues/issue 1369
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#1370 FIX: Topic preview should use token replacement
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
Labels: bug, usability

#1373 Issues/issue 1372
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#1374 Syncing branches
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/sql/08.02.08.SqlDataProvider
Labels: tasks

#1377 TASK: Update DNN Platform Dependency to 9.11.00
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForumsTests/DnnCommunityForumsTests.csproj
  Dnn.CommunityForumsTests/ReferencedAssemblies/DotNetNuke.Tests.Utilities.dll
Labels: dependencies, tasks
