Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2025-01, with the labels that each got.

#1227 FIX: Replace null CreatedOnDate with minimum SQL date when creating Forum User in activeforums_UserProfiles
  Dnn.CommunityForums/Controllers/ForumUserController.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
Labels: bug

#1225 Tasks/release 8.2.0 prep
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/License.txt
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#1230 FIX: Social integration exceptions
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/Controllers/ForumController.cs
Labels: bug

#1231 ENH: Save Social Integration forum security using common permissions
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/ForumSettings.ascx.cs
Labels: enhancement

#1236 FIX: Issues with email notifications
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/class/Settings.cs
  Dnn.CommunityForums/components/Controls/ControlUtils.cs
Labels: bug

#1237 Tasks/release updates 8.2.1
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#1238 Syncing branches for 8.2.1 GA release
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/class/Settings.cs
  Dnn.CommunityForums/components/Controls/ControlUtils.cs
Labels: tasks

#1244 FIX: Empty ReplyEditor template delivered during new install
  Dnn.CommunityForums/08.02.02.txt
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/config/templates/ReplyEditor.ascx
  Dnn.CommunityForums/themes/community-bootstrap/templates/ReplyEditor.ascx
Labels: bug, themes, installer

#1247 FIX: Various UI issues with 8.2 release
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/Entities/AuthorInfo.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx
  Dnn.CommunityForums/sql/08.02.02.SqlDataProvider
Labels: bug, usability

#1249 Tasks/8.2.2 release prep
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#1250 Syncing branches
  Dnn.CommunityForums/08.02.02.txt
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Entities/AuthorInfo.cs
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/components/Topics/TopicsController.cs
  Dnn.CommunityForums/config/templates/ReplyEditor.ascx
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx
  Dnn.CommunityForums/sql/08.02.02.SqlDataProvider
  Dnn.CommunityForums/themes/community-bootstrap/templates/ReplyEditor.ascx
Labels: tasks
