Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2025-02, with the labels that each got.

#1255 FIX: topic announce start/end dates can be null
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/ViewModels/Topic.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
Labels: bug, usability

#1256 FIX: re-order operations when deleting replies
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/sql/08.02.03.SqlDataProvider
Labels: bug, database

#1257 FIX: Unterminated token creating mangled markup
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
Labels: bug, localization, moderator tools

#1259 FIX: Email notifications / remove HttpContext reference
  Dnn.CommunityForums/Controllers/ForumUserController.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/controls/af_sendto.ascx.cs
  Dnn.CommunityForums/feeds.aspx.cs
Labels: bug

#1265 FIX: Control Panel forum & group admin issues
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
  Dnn.CommunityForums/controls/admin_manageforums_home.ascx.cs
Labels: bug, administrator

#1262 FIX: "Is Approved" flag not set for replies when editing in topic view
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/sql/08.02.03.SqlDataProvider
Labels: bug, database

#1267 Tasks/release prep 9.2.3
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#1268 Syncing branches for 8.2.3 release
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/ForumUserController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
  Dnn.CommunityForums/ViewModels/Topic.cs
  Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
  Dnn.CommunityForums/controls/admin_manageforums_home.ascx.cs
  Dnn.CommunityForums/controls/af_post.ascx.cs
  Dnn.CommunityForums/controls/af_sendto.ascx.cs
  Dnn.CommunityForums/feeds.aspx.cs
  Dnn.CommunityForums/sql/08.02.03.SqlDataProvider
Labels: tasks

#1271 FIX: Botched SQL merge
  Dnn.CommunityForums/sql/08.02.03.SqlDataProvider
Labels: bug, database

#1272 Merging branches again
  Dnn.CommunityForums/sql/08.02.03.SqlDataProvider
Labels: tasks

#1278 FIX: Issues when deleting a topic
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/sql/08.02.04.SqlDataProvider
Labels: bug, database

#1279 ENH: Update unit tests with mocks for DNN objects
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/Entities/LikeInfo.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/Services/Tokens/ForumsModuleTokenReplacer.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/ViewModels/Forum.cs
  Dnn.CommunityForumsTests/Controllers/PermissionControllerTests.cs
  Dnn.CommunityForumsTests/Controllers/TopicPropertyControllerTests.cs
  Dnn.CommunityForumsTests/DnnCommunityForumsTests.csproj
  Dnn.CommunityForumsTests/Entities/ForumInfoTests.cs
  Dnn.CommunityForumsTests/Entities/ReplyItemTests.cs
  Dnn.CommunityForumsTests/Entities/TopicItemTests.cs
  Dnn.CommunityForumsTests/Properties/AssemblyInfo.cs
  Dnn.CommunityForumsTests/ReferencedAssemblies/DotNetNuke.Tests.Utilities.dll
  Dnn.CommunityForumsTests/Services/Tokens/ForumsModuleTokenProvider.cs
  Dnn.CommunityForumsTests/Services/Tokens/TokenReplacerTests.cs
  Dnn.CommunityForumsTests/TestBase.cs
  Dnn.CommunityForumsTests/app.config
  Dnn.CommunityForumsTests/class/UtilitiesTests.cs
  Dnn.CommunityForumsTests/packages.config
Labels: tasks, technical debt

#1280 FIX: TopicsView when multiple forums instances
  Dnn.CommunityForums/sql/08.02.04.SqlDataProvider
Labels: bug, database

#1284 FIX: Handle users without UserPortals records
  Dnn.CommunityForums/Controllers/ForumUserController.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/sql/08.02.04.SqlDataProvider
Labels: bug, database

#1285 FIX: Topic View populate DateUpdated
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
Labels: bug

#1291 FIX: Quick Reply replies requiring moderation
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
Labels: bug, moderator tools

#1293 TASK: Don't look for user in HttpContext
  Dnn.CommunityForums/Controllers/ForumUserController.cs
  Dnn.CommunityForums/Controllers/ModerationController.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ForumContentNavigator.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ForumContentTree.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ForumNavigator.cs
  Dnn.CommunityForums/WhatsNew.ascx.cs
  Dnn.CommunityForums/class/SettingsBase.cs
  Dnn.CommunityForums/components/Users/UserController.cs
Labels: technical debt

#1295 TASK: Remove deprecated API usage removed in DNN 10
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/controls/af_attach.ascx.cs
Labels: dependencies, tasks, technical debt

#1297 Tasks/release 8.2.4
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#1298 Syncing branches for 8.2.4
  Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
  Dnn.CommunityForums/App_LocalResources/SharedResources.resx
  Dnn.CommunityForums/Controllers/ForumController.cs
  Dnn.CommunityForums/Controllers/ForumUserController.cs
  Dnn.CommunityForums/Controllers/ModerationController.cs
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/Controllers/ReplyController.cs
  Dnn.CommunityForums/Controllers/TopicController.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ForumContentNavigator.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ForumContentTree.cs
  Dnn.CommunityForums/CustomControls/ServerControls/ForumNavigator.cs
  Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/DnnCommunityForums.csproj
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/Entities/ForumUserInfo.cs
  Dnn.CommunityForums/Entities/LikeInfo.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
  Dnn.CommunityForums/Services/Tokens/ForumsModuleTokenReplacer.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/ViewModels/Forum.cs
  Dnn.CommunityForums/WhatsNew.ascx.cs
  Dnn.CommunityForums/class/SettingsBase.cs
  Dnn.CommunityForums/class/TemplateUtils.cs
  Dnn.CommunityForums/components/Users/UserController.cs
  Dnn.CommunityForums/controls/af_attach.ascx.cs
  Dnn.CommunityForums/controls/af_quickreply.ascx.cs
  Dnn.CommunityForums/sql/08.02.04.SqlDataProvider
  Dnn.CommunityForumsTests/Controllers/PermissionControllerTests.cs
  Dnn.CommunityForumsTests/Controllers/TopicPropertyControllerTests.cs
  Dnn.CommunityForumsTests/DnnCommunityForumsTests.csproj
  Dnn.CommunityForumsTests/Entities/ForumInfoTests.cs
  Dnn.CommunityForumsTests/Entities/ReplyItemTests.cs
  Dnn.CommunityForumsTests/Entities/TopicItemTests.cs
  Dnn.CommunityForumsTests/Properties/AssemblyInfo.cs
  Dnn.CommunityForumsTests/ReferencedAssemblies/DotNetNuke.Tests.Utilities.dll
  Dnn.CommunityForumsTests/Services/Tokens/ForumsModuleTokenProvider.cs
  Dnn.CommunityForumsTests/Services/Tokens/TokenReplacerTests.cs
  Dnn.CommunityForumsTests/TestBase.cs
  Dnn.CommunityForumsTests/app.config
  Dnn.CommunityForumsTests/class/UtilitiesTests.cs
  Dnn.CommunityForumsTests/packages.config
Labels: tasks

#1306 FIX: Layout of Module initailization screen #1304
  Dnn.CommunityForums/controls/_default.ascx
  Dnn.CommunityForums/images/Branding/Logo/DNN-Community-Forums-Logo-Horizontal.png
  Dnn.CommunityForums/images/Branding/Logo/DNN-Community-Forums-Logo-Horizontal.psd
  Dnn.CommunityForums/module.css
Labels: enhancement

#1314 Tasks/issue 1313
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#1315 Syncing branches for 08.02.05 GA
  Dnn.CommunityForums/Classic.ascx.cs
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
  Dnn.CommunityForums/controls/_default.ascx
  Dnn.CommunityForums/images/Branding/Logo/DNN-Community-Forums-Logo-Horizontal.png
  Dnn.CommunityForums/images/Branding/Logo/DNN-Community-Forums-Logo-Horizontal.psd
  Dnn.CommunityForums/module.css
Labels: tasks

#1317 Added missing update to the release notes
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#1318 Syncing branches for the 8.2.5 release
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#1320 FIX: Flood control preventing new user from posting
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForumsTests/class/UtilitiesTests.cs
Labels: bug, usability

#1323 FIX: Icon align in Bootstrap 4
  Dnn.CommunityForums/themes/community-bootstrap/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_forum-view.less
  Dnn.CommunityForums/themes/community-default/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: enhancement

#1321 FIX: Forum View > Sub Forum alignment
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/theme.scss
  Dnn.CommunityForums/themes/community-bootstrap/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_forum-view.less
  Dnn.CommunityForums/themes/community-default/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
Labels: enhancement

#1326 ENH: Use Enter key in search popup
  Dnn.CommunityForums/config/templates/ToolbarSearchPopup.ascx
Labels: enhancement, usability

#1325 FIX: Don't overwrite existing templates
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/Globals.cs
Labels: bug, administrator

#1328 Tasks/issue 1327
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
Labels: tasks

#1329 Syncing branches for the 8.2.6 release
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
  Dnn.CommunityForums/Properties/AssemblyInfo.cs
  Dnn.CommunityForums/ReleaseNotes.txt
  Dnn.CommunityForums/class/ForumsConfig.cs
  Dnn.CommunityForums/class/Globals.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/config/templates/ToolbarSearchPopup.ascx
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/parts/_toolbar.scss
  Dnn.CommunityForums/themes/community-bootstrap/_src/scss/theme.scss
  Dnn.CommunityForums/themes/community-bootstrap/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-bootstrap/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-bootstrap/theme.css
  Dnn.CommunityForums/themes/community-bootstrap/theme.css.map
  Dnn.CommunityForums/themes/community-bootstrap/theme.min.css
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_forum-view.less
  Dnn.CommunityForums/themes/community-default/_src/less/parts/_toolbar.less
  Dnn.CommunityForums/themes/community-default/templates/ForumView.ascx
  Dnn.CommunityForums/themes/community-default/theme-source.zip.resources
  Dnn.CommunityForums/themes/community-default/theme.css
  Dnn.CommunityForums/themes/community-default/theme.css.map
  Dnn.CommunityForums/themes/community-default/theme.min.css
  Dnn.CommunityForumsTests/class/UtilitiesTests.cs
  README.md
Labels: tasks
