Repository DNNCommunity/Dnn.CommunityForums, pull requests merged in 2025-05, with the labels that each got.

#1395 TASK: Convert database columns from NTEXT to NVARCHAR(MAX)
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/sql/09.00.00.SqlDataProvider
Labels: tasks, database

#1399 FIX: Add bracket encoding/decoding to not interfere with token replacement
  Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/Entities/ReplyInfo.cs
  Dnn.CommunityForums/Entities/TopicInfo.cs
  Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForums/controls/af_grid.ascx.cs
  Dnn.CommunityForums/controls/af_search.ascx.cs
Labels: bug, usability

#1402 Clean up images folder with "09.00.00" manifest
  Dnn.CommunityForums/09.00.00.txt
  Dnn.CommunityForums/DnnCommunityForums.dnn
  Dnn.CommunityForums/images/Cancel.gif
  Dnn.CommunityForums/images/add_attach.png
  Dnn.CommunityForums/images/closeX.png
  Dnn.CommunityForums/images/controlbar-black-border.gif
  Dnn.CommunityForums/images/controlbar-white-small.gif
  Dnn.CommunityForums/images/controlbar-white.gif
  Dnn.CommunityForums/images/controlbar2.gif
  Dnn.CommunityForums/images/controlbar3.gif
  Dnn.CommunityForums/images/controlbar4-hover.gif
  Dnn.CommunityForums/images/controlbar4.gif
  Dnn.CommunityForums/images/delete12.png
  Dnn.CommunityForums/images/fast_forward.png
  Dnn.CommunityForums/images/footerback.gif
  Dnn.CommunityForums/images/fullexpand.gif
  Dnn.CommunityForums/images/geckodimmer.png
  Dnn.CommunityForums/images/groups32.png
  Dnn.CommunityForums/images/icon.gif
  Dnn.CommunityForums/images/image_insert.png
  Dnn.CommunityForums/images/image_thumb.png
  Dnn.CommunityForums/images/loader.gif
  Dnn.CommunityForums/images/loader.white.gif
  Dnn.CommunityForums/images/mail.png
  Dnn.CommunityForums/images/mail_error.png
  Dnn.CommunityForums/images/mail_exchange.png
  Dnn.CommunityForums/images/mail_ok.png
  Dnn.CommunityForums/images/rewind.png
  Dnn.CommunityForums/images/settings32.png
  Dnn.CommunityForums/images/sp-actions16.png
  Dnn.CommunityForums/images/sp-tabs.png
  Dnn.CommunityForums/images/status0.png
  Dnn.CommunityForums/images/status3.png
  Dnn.CommunityForums/images/subnavback.gif
  Dnn.CommunityForums/images/zoomin.cur
  Dnn.CommunityForums/images/zoomout.cur
Labels: tasks

#1400 FIX: editing a topic from TopicsView page showing wrong content
  Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
  Dnn.CommunityForums/sql/09.00.00.SqlDataProvider
Labels: bug, database, usability

#1401 FIX: Retrieve attachments for unapproved topics in moderation
  Dnn.CommunityForums/sql/09.00.00.SqlDataProvider
Labels: bug, database

#1414 FIX: HasEditIntervalPassed method issue
  Dnn.CommunityForums/Controllers/PermissionController.cs
  Dnn.CommunityForums/CustomControls/UserControls/WhatsNewRSS.cs
  Dnn.CommunityForums/Entities/ForumGroupInfo.cs
  Dnn.CommunityForums/Entities/ForumInfo.cs
  Dnn.CommunityForums/WhatsNew.ascx.cs
  Dnn.CommunityForums/class/Utilities.cs
  Dnn.CommunityForumsTests/Controllers/PermissionControllerTests.cs
  Dnn.CommunityForumsTests/Entities/TopicItemTests.cs
  Dnn.CommunityForumsTests/Services/Tokens/TokenReplacerTests.cs
  Dnn.CommunityForumsTests/class/UtilitiesTests.cs
Labels: bug
